### PR TITLE
Return http 204 when webhook validation fails

### PR DESCRIPTION
**Pull request by reykjalin**
# Changes proposed in this Pull Request:

See #1437. The changes are identical, we just applied the PR to the wrong branch before.

# Testing instructions

See #1437.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by reykjalin** [comment]
@asumaran I think it's safe to test this very lightly, if at all. If we can send an invalid webhook from Stripe to verify the response that's great; otherwise just reviewing the code will be fine I think 🙂

**Review by asumaran — COMMENTED** [review]
> I think it's safe to test this very lightly, if at all. If we can send an invalid webhook from Stripe to verify the response that's great; otherwise just reviewing the code will be fine I think

Alright then, code LGTM!

Other than that, is the change in `.cache/woorelease.phar` intended?

**Comment by reykjalin** [comment]
>Other than that, is the change in .cache/woorelease.phar intended?

Ugh no, leftover from a different PR 🤦‍♂️ 

Fixed in 156042ee7c53f79ec4dff88992416539bda9b6f7

**Review by asumaran — APPROVED** [review]
LGTM

**Pull request merged**
