### PR TITLE
[Payment Request] Update total when auto-selecting shipping option

### LINKED ISSUE #121: Payment Request API: Total should reflect updated shipping
#### What I expected

In Payment Request, when selecting a shipping address, the shipping rate is recomputed based on the different store rules and the Total should also be modified by that amount.

#### What happened instead

The shipping rate is updated, but the total does not take into account the shipping rate.

#### Steps to reproduce the issue

* Trigger the Payment Request UI (I used Chrome for Android on [https://woocommerce.paymentrequest.show](https://woocommerce.paymentrequest.show) and "bought" something).
* Choose a shipping option and see that the total does not reflect the shipping rate.

In the following screenshot, the total should be $6.00
paymentrequestshipping

#### Notes

Here is an example of how to recompute the "details" (including the total) when the shipping rate changes: https://googlechrome.github.io/samples/paymentrequest/dynamic-shipping/

cc @claudiosanches given the previous contributions.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by madmath**
Fixes #121  .

#### Changes proposed in this Pull Request:
- When only one shipping option is available, it is pre-selected (existing behavior)
- In that case, this change will update the shipping details to reflect the new total.

-------------------
- [X] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [X] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

#### Notes

See discussion on issue #121. This solves the original report.

### CODE REVIEW

**Comment by madmath** [comment]
Friendly ping, thanks!

**Comment by roykho** [comment]
Hi @madmath - thanks for the PR however in my test, this does not resolve the issue. I have only one shipping ( flat rate ) and it does not get added to the total after selecting the address.

**Comment by madmath** [comment]
Thanks Roy!

I set up my code on https://woocommerce.paymentrequest.show, can you test there? I only have 1 flat rate option set up. Thanks again

**Comment by roykho** [comment]
@madmath it certainly is working your site. Strange. I will have to debug this on my site and see.

**Comment by madmath** [comment]
Let me know, I definitely want the solution to work everywhere :)

**Comment by roykho** [comment]
@madmath ah false alarm. It was a caching issue. Then I tested by opening up an incognito tab and it is working as expected. Thanks for the PR!

**Pull request merged**
