### PR TITLE
Add list of payment methods that are not included for merchant

### LINKED ISSUE #2173: Additional payment methods
## Description

Add a list of the payment methods that are not included in the merchant's capabilities.

image

## Acceptance criteria

- We can see a list of payment methods next to the "Get more payment methods" button, if there is any

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes #2173

## Changes proposed in this Pull Request:

This PR adds a list of payment methods that are not included for the merchant. It helps the merchant identify what other payment methods are not included for their store.

image

## Testing instructions

1. Ensure the plugin ([woocommerce-gateway-stripe](https://github.com/woocommerce/woocommerce-gateway-stripe)) is [installed and configured according to the docs](https://woocommerce.com/document/stripe/#setup-and-configuration).
2. Go to `wp-admin > WooCommerce > Settings > Payments > Stripe`.
3. In the `Payment methods` section (see image above), verify that the unavailable payment methods' icons appear at the bottom, next to the `Get more payment methods` button. Also note that if more than 3 payment methods are not available, a `+ # more` text element appears.

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by lovo-h** [comment]
Rebasing off of `develop` branch to be up-to-date.

image

**Review by cesarcosta99 — APPROVED** [review]
LGTM and tests well 🚢

**Comment by lovo-h** [comment]
@cesarcosta99, we discussed this a bit on Slack and decided that only the "unavailable" payment methods' icons should be displayed in the list. That's to differentiate from "disabled" payment methods.

The reason is that we do not want the payment method's icon to appear twice in the section. Good call 👍

**Review by cesarcosta99 — APPROVED** [review]
Looks good and tests well again 🎉

**Pull request merged**
