### PR TITLE
Update version to 4.5.3

### LINKED ISSUE #1325: Release 4.5.3

### PR DESCRIPTION
**Pull request by allendav**
Fixes #1325

### CODE REVIEW

**Review by luizreis — APPROVED** [review]
@allendav - looks good, but we should probably run `npm run build` before merging this to update the `POT` files and `package-lock.json`, which still have the `4.5.3` version.

Once #1259 is merged, and this PR is rebased and built :shipit:

**Comment by dechov** [comment]
Unless I'm overlooking something, the version bump shouldn't be needed for the next release, which can go out as `4.5.3`.

**Comment by allendav** [comment]
Redoing this as 4.5.3. I forgot it hadn't gone out yet.

**Review by luizreis — APPROVED** [review]
Thanks for catching the unnecessary version bump, @dechov!

@allendav - LGTM :shipit:

**Pull request merged**
