### PR TITLE
remove feature flag

### LINKED ISSUE #2379: StripeLink: Remove feature flag
Before release, we need to remove the `_wc_stripe_feature_link` feature flag implemented in #2370 . 
This was needed to hide the Link features from regular customers until all features are fully implemented.

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes #2379 

## Changes proposed in this Pull Request:

Remove `_wc_stripe_feature_link` Link feature flag 

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Review by dmvrtx — APPROVED** [review]
Looks good to me. Does it have to go to the change log though?

**Comment by dpaun1985** [comment]
> Looks good to me. Does it have to go to the change log though?

Good question. I will ask Fractal about this. Thank you, @dmvrtx !

**Review by anu-rock — COMMENTED** [review]
There are a few JS linting errors here:
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2387/files

Otherwise looks good!

**Comment by dpaun1985** [comment]
> There are a few JS linting errors here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2387/files
> 
> Otherwise looks good!

Fixed. thank you!

**Review by anu-rock — APPROVED** [review]
LGTM after the fixes for linting issues 🎉

**Review by cesarcosta99 — APPROVED** [review]
LGTM! I agree it'd be best to remove the changelog entry, especially having `Add - Stripe Link payment method option in admin`, which tell folks it's being released 👍

**Pull request merged**
