### PR TITLE
[Wallets] Cash App Pay - Add subscriptions and token support

### LINKED ISSUE #3141: [Wallets] Process payments when using Cash App
### Description 

Process payments using Cash App. Payments should be accepted on: 

- [x] Block checkout
- [x] Classic/Shortcode checkout
- [x] Pay for order page.

Feel free to split this task into smaller issues to unblock others or if the workload requires it. 

### Notes:

- Cash App foundational code is added via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3140
- Foundational JS code that will be necessary to support Cash App payments is being added in Mayisha's PR - https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3138

### LINKED ISSUE #3155: [Wallets] Cash App Payments - Add subscription support
Allow shoppers to pay with [CashApp](https://docs.stripe.com/payments/cash-app-pay) when purchasing subscription products. 

```[tasklist]
### Tasks
- [x] Purchase simple subscriptions.
- [ ] ~~Purchase free trial subscriptions.~~ https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3171
- [x] Process renewal orders.
- [x] Pay for failed renewals manually.
- [x] Renew a subscription early.
- [ ] _Optional_. Add payment method via my account. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3179
- [x] View payment method information from customer's view subscription page.
- [x] Add token support - payment methods that support subscriptions need to implement a `WC_Payment_Token`.
```

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3155

## Changes proposed in this Pull Request:

This PR adds support for storing Cash App tokens and using Cash App Pay to purchase and renew subscriptions. 

| Screenshot 2024-05-30 at 4 43 37 PM | Screenshot 2024-05-30 at 4 42 20 PM |
|--------|--------|

### Setup

1. Checkout this branch and make sure to build assets (eg `npm run build`). 
1. Change your Stripe Plugin credentials to a US based account.
2. Change your store currency to USD.
4. Enable Cash App Pay from the Stripe payment methods screen.
5. Your site will need to be remotely available to webhooks via `ngrok` or Jurassic Ninja. At the moment Cash App requires webhooks to process payments. 

### Tokens

1. Enable payments via saved cards in your Stripe plugin settings.
2. Place a standard product in your cart. 
3. On checkout select **Cash App Pay**
4. Check the **Save payment information**.. checkbox
6. Click the **Place Order** button
7. Using your mobile's camera scan the QR code and go to the Stripe hosted URL. 
8. Authorize the purchase.
9. When you land on the order receive page, place a product in your cart again.
10. Return to the checkout page. 
11. Note you now have a saved payment method with Cash App Pay. 

<p align="center">
Screenshot 2024-05-30 at 5 10 11 PM
</p>

12. Complete the purchase using the saved payment method. 
13. Verify in the Stripe Dashboard that the payment was successful. 

**Additional tests**
1. Test on the block and shortcode checkouts. 
13. Test with saved payment methods off in the Stripe settings to make sure the token isn't saved.  

### Subscriptions

0. Install and activate the WooCommerce Subscriptions plugin.
1. Create at least 1 of the following subscription products:
   - Simple monthly product. 
   - Free trial. 
   - Sign up fee.

**New token**
2. Add the **simple subscription product** to your cart. 
3. Complete the checkout using a **new Cash App payment method**.
4. Confirm the order is successfully paid and the subscription is active. 
5. From the **WooCommerce → Subscriptions** page edit the subscriptions purchased with Cash App. 
6. From the actions dropdown select **Process Renewal**
7. Verify the subscription renewal order is paid in the Stripe dashboard. 

**Saved token**
8. Add the **simple subscription product** to your cart again. 
9. Use the saved Cash App token to complete the payment. 
10. Confirm the order is successfully paid and the subscription is active. 
11. From the **WooCommerce → Subscriptions** page edit the subscriptions purchased with Cash App. 
12. From the actions dropdown select **Process Renewal**
14. Verify the subscription renewal order is paid in the Stripe dashboard.

> [!note]
> This PR doesn't add support for free trial products and changing a subscription's payment method to Cash App. Cash App won't appear available on the checkout when the cart is $0 and it won't appear on the Change payment method screen. Support for these subscription flows will be added in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3171.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply) - **doesn't apply**
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Review by mattallan — COMMENTED** [review]
Kudos @james-allan for working on this! I ran out of time to do a proper code review before reaching my EOD, however, I ran through most of the subscription flows on this branch and have to say amazing work on this PR !!

I only found a couple of small issues but nothing overly broken with this 💯 👏 !!

- [x] Purchase a regular product and save a new Cash App token 
- [x] Purchase a regular product using the saved Cash App token
- [x] Purchase a subscription product with saved Cash App token
    - [x] Confirm renewal is processed
- [x] Purchase a subscription product with new Cash App token
    - [x] Confirm renewal is processed
- [x] Renew early
    - [x] Via Modal
    - [x] Via Checkout
- [x] :x: View My Account > Subscription
    - [x] Payment method shows as "N/A"
image
- [x] Purchase a synced subscription
    - [x] No initial payment (not synced to today and no protation). Confirmed no Cash App on checkout
    - [x] With initial payment (not synced to today but prorated amount). Purchased with Cash App
    - [x] With initial payment (synced to today)
- [x] Purchase a free trial subscription. Confirmed Cash App wasn't available
- [x] :x: Change a subscriptions payment method from Stripe Card -> Cash App
    - [x] Error when submitting checkout: 
image
- [x] Change a subscriptions payment method from Cash App -> Stripe Card

**Comment by james-allan** [comment]
Thanks for the initial review Matt :) 

> ❌ View My Account > Subscription
 Payment method shows as "N/A"

I've fixed this in [b1add62](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3156/commits/b1add62d191e2b765bead83726c960e29ea74a58). 

> ❌ Change a subscriptions payment method from Stripe Card -> Cash App

Changing a subscription's payment method to Cash App is a problem. The error you mentioned was caused by a different issue but after resolving that, I then received this error on attempting to change a subscription to a saved cash app token. 

Screenshot 2024-06-03 at 11 07 11 AM

This is the same error which led to us disabling Cash App when paying for $0 carts (ie free trials). You can find internal discussions about this issue here: p1717070220785199/1716833472.084429-slack-C055WHLA98D

The problem is we cannot setup intents and pass a saved Cash App payment method. This is unlike Cards. Because of this we decided to disable Cash App when paying for free trials. We will also need to remove the ability to change a subscription's payment method to Cash App until we find a solution to that setup intent issue with Cash App tokens. I've done that in [d83d7bf](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3156/commits/d83d7bf9f6f43c0060718fa43881ab7f20a4d18c).

**Comment by james-allan** [comment]
I've filed the issue to fix the free trial and change payment method flow here. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3171

**Review by diegocurbelo — APPROVED** [review]
Thanks for working on this @james-allan, it looks amazing 👏🏼 

The code looks great, I really liked the inclusion of the `deprecated` notice in `get_account_saved_payment_methods_list_item_sepa` 💯 

It tests really well too, tested all the flows especially those that were not working for Matt, and they are working flawlessly:
Screenshot 2024-06-05 at 6 10 42 PM

I did find an edge case with the `Add payment method` page.
If you
- add a normal product to the cart **(this is the important step)**
- go to `My account` > `Payment methods`
- the `Add payment method` button is there, and Cash App is listed as an option:

image

Without a product in the cart everything works fine, and when I try to access the page directly the proper notice is shown:
Screenshot 2024-06-05 at 6 22 02 PM

I'm approving the PR, in case you want to fix it on a different (and smaller) PR; everything else works as expected so happy to re-review this PR if you prefer to include that edge-case fix here 🤷🏼

**Comment by james-allan** [comment]
> I'm approving the PR, in case you want to fix it on a different (and smaller) PR; everything else works as expected so happy to re-review this PR if you prefer to include that edge-case fix here


That sounds like a good approach, rather than have you come back and test again for that specific change, I'll file an issue and fix that other issue separately.

**Pull request merged**
