### PR TITLE
Add missing customer ID to subscriptions before processing payment

### LINKED ISSUE #1072: Updating recurring payment method from non-Stripe to Stripe - Customer ID token is not saved to the subscription
**Describe the bug**
Related to WooCommerce Subscriptions - when updating recurring payment method via My Accounts > Payment Methods from a non-Stripe payment method to Stripe, no Customer ID token is saved on the subscription. Subsequent recurring payments fail for a lack of Customer ID token.

A customer profile is correctly created in Stripe (in the case of a new Stripe customer) and the Source ID token is correctly saved on the subscription.

Seen in 2447640-zen

**To Reproduce**

1. Purchase a subscription through a non-Stripe automatic recurring payment solution (i.e. PayPal Checkout w/Reference Transactions)
2. Go to **My Account > Payment Methods** and add a new Stripe payment method
3. Be sure to select the option for "Update the Payment Method used for all of my active subscriptions (optional)."
4. Go to the subscription and click "Billing Details" to edit
5. See that no Customer ID token has been saved to this subscription

This will cause future renewal payments for this subscription to fail. 

**Expected behavior**
When updating the recurring payment method on an existing subscription from a non-Stripe option to Stripe, both the Customer ID token and the Source ID token should be saved to the subscription. 

**Screenshots**
https://cld.wthms.co/VhdYxs
Full Image: https://cld.wthms.co/VhdYxs+

https://cld.wthms.co/NIObsv
Full Image: https://cld.wthms.co/NIObsv+

**Environment (please complete the following information):**
 - WordPress v. 5.2.4
 - WooCommerce version 3.7.1
 - Stripe v. 4.3.0
 - PayPal Checkout v. 1.6.17
- Browser / OS - Any

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #1072.

Address subscriptions that might not have a Stripe customer ID when renewing. This could happen if the customer updated their recurring payment method (see issue #1072). PR #1106 proposed a fix for new recurring payment updates. This one aims to address existing subscriptions that cannot be renewed and have to be manually updated by merchants/customers.

#### Changes proposed in this Pull Request:
- Add missing customer ID to subscriptions before processing payment

#### Testing instructions:
1. Purchase a subscription through a non-Stripe payment method using a version before #1106 
2. Go to My Account > Payment Methods and add a new Stripe payment method
3. Be sure to select the option for "Update the Payment Method used for all of my active subscriptions (optional)."
4. Go to the subscription and click "Billing Details" to edit
5. See that no Customer ID token has been saved to the subscription
6. Attempt to process the renewal for that subscription
    - It should fail since there's no Customer ID
6. After replicating on this branch you should see the renewal was successful and the customer token is set for future ones
-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by v18** [comment]
Some hopefully helpful notes: The reason there is a problem when processing the renewal is because that action is the same as updating the subscription (for example when adding a customer ID, etc) - it's just "updating the subscription". When the subscription is updated, the function `validate_subscription_payment_meta` is called to validate all the fields, regardless which actual action the user wants to perform. It's called by the hook `woocommerce_subscription_validate_payment_meta`. I haven't looked yet to see if it's possible to figure out which action the user is trying to perform to have a different validator, or make them run in a different order  🤔 

There is also a related PR here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1040

This is what I know so far. I'll take another look soon & report back.

**Comment by AashikP** [comment]
@v18  just pinging to check if this PR is going to get attention soon.

**Comment by v18** [comment]
I tested this again, and the subscription renewal was able to go through. However, this error message still showed up: `Error updating some information: A "Stripe Customer ID" value is required.`

**Comment by v18** [comment]
Great job, the changes look good to me, @luizreis!

I have a suggestion for fixing the validation error, by providing an extra check in the validation function `validate_subscription_payment_meta()`, something like

`isset( $_POST['wc_order_action'] ) && 'wcs_process_renewal' !== $_POST['wc_order_action']`

here (as well as in the SEPA compat class):

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/aa8082a71cbb634fa2a07b001fb75acf9d02fc3c/includes/compat/class-wc-stripe-subs-compat.php#L454

This ensures that we are not dealing with a renewal before validating. For the renewal, we are not trying to save the details to the subscription, and they'll be overwritten anyway. For any other type of update, it should work as usual.

One problem I can see is that a store owner may both change the subscription details _and_ process the renewal. I'm not sure how frequently this happens and if we need to worry about it. One way around it is to check the previous details with the new details instead of checking for `'wcs_process_renewal' !== $_POST['wc_order_action']`, but I didn't see a great way of doing that. Do you have any thoughts on this @james-allan ?

If you see a better way to solve this, I'm happy to take a look.

**Comment by james-allan** [comment]
> I have a suggestion for fixing the validation error, by providing an extra check in the validation function `validate_subscription_payment_meta()`, something like: 
> 
> ```
> isset( $_POST['wc_order_action'] ) && 'wcs_process_renewal' !== $_POST['wc_order_action']
> ```

Yeah, that would work for this specific scenario and makes sense given the subscription will be updated during the request.

> This ensures that we are not dealing with a renewal before validating. For the renewal, we are not trying to save the details to the subscription, and they'll be overwritten anyway. For any other type of update, it should work as usual.

As far as I can tell the payment meta validation and setting happens before the renewal action is processed. Is that right? If so I don't think there's a concern with updating the customer ID and then overriding the one the user set.

The only other workaround I could think of is to patch Subscriptions so we don't validate the payment meta if the user hasn't changed anything.

**Comment by allendav** [comment]
@luizreis - next steps? could @vbelolapotkov take this over for 4.3.3?

**Comment by luizreis** [comment]
@allendav, @vbelolapotkov 

> @luizreis - next steps? 

This PR should be working. The only step missing would be to suppress the alert regarding not having a Stripe ID when merchants manually trigger a subscription renewal. This alert shows up even though the renewal is successfully processed, as it is related to clicking the "Update" button with a blank customer ID.

The ID is added later, outside of the `woocommerce_subscription_validate_payment_meta hook`, but in time for the subscription renewal to work. Automatic renewals do not have this issue, as they do not trigger a subscription update/form submission.

> could @vbelolapotkov take this over for 4.3.3?

Sure! I started this PR during a janitor rotation, but haven't worked on it after that since we weren't sure of when this would be shipped.

**Comment by vbelolapotkov** [comment]
@luizreis, thank you for sharing! I'll get back to you when start working on it.

**Comment by vbelolapotkov** [comment]
> I tested this again, and the subscription renewal was able to go through. However, this error message still showed up: Error updating some information: A "Stripe Customer ID" value is required.

@v18 I've tried to reproduce it with no luck (WC 4.0.1). I haven't noticed such an error message either with the plugin version 4.3.1 or with the current branch.

**Pull request merged**
