### PR TITLE
feat: add payment method icons

### PR DESCRIPTION
**Pull request by frosso**
## Changes proposed in this Pull Request:

Adding some base payment method icons for reuse.

## Testing instructions

- Ensure you have the `_wcstripe_feature_upe_settings` feature flag enabled
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe
- You should see a list of icons with their 2 different sizes
Screen Shot 2021-08-20 at 12 34 12 PM

### CODE REVIEW

**Review by cesarcosta99 — COMMENTED** [review]
Code is neat and tests well! 🎉 

There is just one little detail that I think we can improve here. What if we move the SVG files to a new `images` folder? That would keep the project structure more organized and consistent in case more images are added.

**Review by tommyshellberg — DISMISSED** [review]
Looks good and tests well 👍 
I do like the idea of keeping the SVG file as close to the component as possible, but I can see how bulk updating them would be easier if they were all in `assets/images/payment-icons`, for instance.

**Comment by frosso** [comment]
@cesarcosta99 and I chatted about this over Slack earlier - the SVGs are transformed to blobs via Webpack (instead of being assets like in the `images` folder). The `images` folder is used for assets that are loaded by the browser via an additional request, so in this case, having the SVGs next to the jsx would help a bit with colocation (since they're not loaded via an additional URL request).

**Comment by frosso** [comment]
@tommyshellberg @cesarcosta99 sorry both, but it looks like your review got dismissed once I resolved the merge conflicts - feel free to take another look!

**Review by tommyshellberg — APPROVED** [review]
👍

**Pull request merged**
