### PR TITLE
Fix redirection on failures when paying with Cash App

### LINKED ISSUE #3170: [Cash App] Fix lack of feedback when a payment fails
If you try to pay using Cash App and the payment fails, the store will redirect you to the "order received" page without additional information. It will look like the payment succeeded.

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #3170

## Changes proposed in this Pull Request:

If you try to pay using Cash App and the payment fails, the store will redirect you to the "order received" page without additional information. It will look like the payment succeeded. This PR improves this flow by checking the processing result and redirecting the shopper back to the cart with the error message. This works only on mobile since [it is the only flow that returns the result as a query param in the URL.](https://docs.stripe.com/payments/cash-app-pay/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#handle-redirect)

## Testing instructions

- Checkout to this branch on your local environment (`fix/wallet-redirect-on-failure`)
- Set your store currency to US, enable Cash App payments on your wp-admin and the Stripe dashboard
- Enable external access to it (using something like [Ngrok](https://dashboard.ngrok.com/))
- Open your store on your phone
- Place a simple product in the cart and go to the checkout.
- Select Cash App Pay
- Click Place order.
- On the Stripe-hosted test page, choose to fail the payment.
- On this branch, you will be redirected back to the cart page with an error:
https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/51f55dd1-52d5-4c1f-bc45-9261d31abeb1

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Thanks for woking on this @wjrosa!

The code looks great.. but the red notice is not showing for me 😢 . When I reload the page, I get an error message (or explanation) ,but is different from the screenshot.

I created a release zip and tested it on a JN site (in case it was something with my local env).
Just to confirm, I taped the "fail test payment" button on this page:

IMG_1202

image

With the Storefront theme:
image 2

**Comment by wjrosa** [comment]
This is weird. I just tested again on my local env, and it worked as expected. Then I tested on a new JN site and got the same result:
https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/8a7bf577-f3ba-41b9-ae7f-3b0249b4eae3
I am sending attached my release.
[woocommerce-gateway-stripe.zip](https://github.com/user-attachments/files/15587075/woocommerce-gateway-stripe.zip)

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Thank you @wjrosa, created a new site (https://scrumptiously-round.jurassic.ninja) and it's working as indicated now, so it might have been a cache problem 🤷🏼

But now that I look at both flows closely, in my failed tests before, the redirect took me to the order page, but this time is redirecting me to the cart (which is empty in case of a payment error as the order was already created). Why not show the message on the order received page?

The message says: "try again or try an alternate payment method", which makes sense for the order page (there is a try again button there), but in the empty cart case it might be confusing.

**Comment by wjrosa** [comment]
> Thank you @wjrosa, created a new site (https://scrumptiously-round.jurassic.ninja) and it's working as indicated now, so it might have been a cache problem 🤷🏼
> 
> But now that I look at both flows closely, in my failed tests before, the redirect took me to the order page, but this time is redirecting me to the cart (which is empty in case of a payment error as the order was already created). Why not show the message on the order received page?
> 
> The message says: "try again or try an alternate payment method", which makes sense for the order page (there is a try again button there), but in the empty cart case it might be confusing.

Yeah, it makes sense. I just did it that way following [the PayPal implementation](https://github.com/woocommerce/woocommerce/blob/76d2b205e51311dac14fe83b96eaf7c96ce44596/plugins/woocommerce/includes/gateways/paypal/class-wc-gateway-paypal.php#L129) as a reference. I found 2 issues when changing/moving the error message:
- Order received page does not show error notices. I even tried to add `<?php wc_print_notices(); ?>` as a possible fix to submit to the main WC repository, but it had to effect 🤔 
- The original CSS classes for errors are not being displayed correctly anymore (`woocommerce-notice`, `woocommerce-notice--error`, `woocommerce-thankyou-order-failed`, `woocommerce-thankyou-order-failed-actions`). So default error messages are being displayed as plain text

I did copy the original content for failures in the order received page from [here](https://github.com/woocommerce/woocommerce/blob/76d2b205e51311dac14fe83b96eaf7c96ce44596/plugins/woocommerce/templates/checkout/thankyou.php#L33). Just changed the classes to the new ones.

That's how it is shown now:
https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/915f29f1-977e-4f58-90b4-28791e729e10

**Review by diegocurbelo — APPROVED** [review]
Thanks for making these changes so quickly @wjrosa!

It works perfectly now (tested with Storefront and the default themes) 🚢 
image

**Pull request merged**
