### PR TITLE
Tweak payment method form transitions

### PR DESCRIPTION
**Pull request by dechov**
When there isn't room for the Stripe payment method label and all of the acceptance icons (6 if USD, 3 otherwise), the wrapped icons affect the width of the payment form that follows during the payment method transition:

overflow-hidden-during-slide

(Tested by having multiple payment methods enabled and switching between them.)

#### Changes proposed in this Pull Request:

https://github.com/woocommerce/woocommerce-gateway-stripe/commit/a5448aa5bcad28f4200d9c281d71e8a2834c0f90 clears the floated icons so that the width of the payment form isn't affected during the WC core slide transition (during which `overflow: hidden` is set):

Screen Shot 2019-07-30 at 9 58 19 PM

Another possibility considered was a clearfix added to label, but it's too much vertical space:

clearfix

Yet another is clearfix with margins tweaked, hard to make work independent of # of icons per row:

clearfix-margin-tweak

(I also slightly tweaked the size of the icons because I figured they could stand to be smaller, and also to make 3 fit across with the default title and standard desktop width.)

Also, when loading, https://github.com/woocommerce/woocommerce-gateway-stripe/commit/164dd6614d211c6fc2b06df12133f6d634a1523d adjusts placeholder styling between containers being rendered and elements being mounted:

`master` | this branch
-- | --
 | 

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by v18** [comment]
From a visual perspective the follow seems like a better option to me personally, but I am not a designer ;) 

> Another possibility considered was a clearfix added to label, but it's too much vertical space



The current style works in all browsers and mobile 👍 .

I'm going to add the 'Needs Design' label and ask a design for some quick input. Otherwise 🚢 .

**Comment by v18** [comment]
From @laurendavissmith - we need to test this on different themes.

From @LevinMedia 👍 

> Two other thoughts... could we run the icons in a row directly below the credit card radio button?

> lastly... maybe based on what Lauren is saying, give people the option to turn off the icons all together?

To do:
- [ ] test on different themes
- [ ] try: icons in a row
- [ ] feasible to let user remove icons?! (ooh, is probably not hard for a store owner to do using custom css...)

**Comment by v18** [comment]
Related: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/702

**Comment by v18** [comment]
Also from @LevinMedia:

> of the three options, the third looks best IMO

**Comment by dougaitken** [comment]
Can we look at turning off the icons as a single checkbox, maybe even only for "smaller screens"? 

> ooh, is probably not hard for a store owner to do using custom css...

@v18 - IIRC it is possible to remove all the icons since I know you can change the icons using this type of snippet ([taken from the docs](https://docs.woocommerce.com/document/stripe/#section-39))

```
add_filter( 'wc_stripe_payment_icons', 'change_my_icons' );
function change_my_icons( $icons ) {
        // var_dump( $icons ); to show all possible icons to change.
    $icons['visa'] = '<img src="https://shipyouridea.com/wp-content/plugins/woocommerce/assets/images/icons/credit-cards/visa.svg" />';
    return $icons;
}
```

**Comment by allendav** [comment]
This is working better now with the latest version of Storefront (2.5.8). Closing without merging.

**Pull request closed without merging**
