### PR TITLE
Update readme text and upload new screenshots

### PR DESCRIPTION
**Pull request by johndcoy**
## Changes proposed in this Pull Request:

Fulfill Stripe's request to update the content on the readme.txt to reflect new content for WordPress.org , along with new screenshots. 

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Review by annemirasol — APPROVED** [review]
Hi @johndcoy, thanks for working on this!

Some non-blocking questions:

- Are we intentionally removing the FAQ item `= Does this support recurring payments, like for subscriptions? =`? The new description does mention supporting subscriptions -- just making sure.

- `screenshot-4.png` ([this](https://raw.githubusercontent.com/woocommerce/woocommerce-gateway-stripe/5963e411d7509eb27266a8462ee15f7afe22cd12/wordpress_org_assets/screenshot-4.png)) looks awfully low res, and could also can benefit from cropping. Is it possible to get a better one?

**Comment by johndcoy** [comment]
> * Are we intentionally removing the FAQ item `= Does this support recurring payments, like for subscriptions? =`? The new description does mention supporting subscriptions -- just making sure.

@annemirasol It was more that Stripe didn't put repeating feature into into the FAQ, but if you think this is a top question and we should have it, they okay with adding in the FAQ as well.

> * `screenshot-4.png` ([this](https://raw.githubusercontent.com/woocommerce/woocommerce-gateway-stripe/5963e411d7509eb27266a8462ee15f7afe22cd12/wordpress_org_assets/screenshot-4.png)) looks awfully low res, and could also can benefit from cropping. Is it possible to get a better one?

Nice catch!  I've replaced it with a new image from Stripe.

**Comment by annemirasol** [comment]
@johndcoy 

> > * Are we intentionally removing the FAQ item `= Does this support recurring payments, like for subscriptions? =`? The new description does mention supporting subscriptions -- just making sure.
> 
> @annemirasol It was more that Stripe didn't put repeating feature into into the FAQ, but if you think this is a top question and we should have it, they okay with adding in the FAQ as well.
> 

I'm okay with it, as is.

> > * `screenshot-4.png` ([this](https://raw.githubusercontent.com/woocommerce/woocommerce-gateway-stripe/5963e411d7509eb27266a8462ee15f7afe22cd12/wordpress_org_assets/screenshot-4.png)) looks awfully low res, and could also can benefit from cropping. Is it possible to get a better one?
> 
> Nice catch! I've replaced it with a new image from Stripe.

Thanks, it looks much better. 

Non-blocking at all, and feel free to merge these changes already -- I realized `screenshot-2.png` is just of the cart page and doesn't exactly show anything Stripe gateway extension-related. Do we want that included?

**Comment by johndcoy** [comment]
> Non-blocking at all, and feel free to merge these changes already -- I realized `screenshot-2.png` is just of the cart page and doesn't exactly show anything Stripe gateway extension-related. Do we want that included?

Yes, the same applied to screenshot 6. These are images provided by Stripe along with the caption for each. The caption should support the specific images.

**Pull request merged**
