### PR TITLE
Add filter to change the refund request sent to the server.

### PR DESCRIPTION
**Pull request by msaggiorato**
Simple proposal. Not related to any issues.

#### Changes proposed in this Pull Request:
-We're adding the `wc_stripe_generate_refund_request` filter to allow filtering of the request sent to stripe at the time of the refund. It's useful when you implement "destination" parameters on the charge (with the `wc_stripe_generate_payment_request` filter).

### CODE REVIEW

**Comment by roykho** [comment]
There is already a filter for all requests using `woocommerce_stripe_request_body`

**Comment by msaggiorato** [comment]
But there's no filter for the refund specifically (so you can't get the order, from the `woocommerce_stripe_request_body` filter). 

This serves the same purpose of the `wc_stripe_generate_payment_request` filter (which is also preceeding the `woocommerce_stripe_request_body`)

**Comment by roykho** [comment]
You can get the API to know if it is a refund or not. Probably just can't get the order. I will think of something in the future to pass the order to the request on every request so we can add one filter instead of adding one for types of request.

**Comment by msaggiorato** [comment]
Ok, so for the time being we won't have this filter merged.

I thought this would be a simple fix with no repercussions on other plugins

**Comment by roykho** [comment]
The thing is, once you introduce a new filter, it is very hard to remove in the future. So we'll definitely look into a universal one.

**Comment by msaggiorato** [comment]
Ok. When do you think we'll have something like this?

**Comment by roykho** [comment]
Most probably in 4.1. But no ETA at this time.

**Comment by msaggiorato** [comment]
Thanks,

Sorry to bring this up again, but i see that there are a lot of specific filters that were added in the 4.0.0 instead of a more global solution. Eg: `wc_stripe_p24_source`, `wc_stripe_ideal_source`, `wc_stripe_alipay_source`, etc. Also, unrelated to sources: `wc_stripe_create_customer_args`.

All of these seem to have been added in 4.0, and all of these are more specific versions of filters that can be then filtered in the `woocommerce_stripe_request_body`.

I truly believe that the more granular we get, the better it is. It's good to have a global filter aswell, but having more granularity probably won't have a negative impact.

**Comment by roykho** [comment]
As I said, I will think of something that is the most appropriate. Meanwhile you can actually use the filter I mentioned. After looking at it, `order_id` is passed in the `$request` variable so you can use that `order_id` to get at the order.

**Comment by msaggiorato** [comment]
Hey Roy,

The $request variable according to what i see [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L697-L726) (code in your master branch, not on my fork)

Only has

```PHP
$request['amount'] = xxx;
$request['metadata'] = array(
    "reason" => xxx,
)xxx;
$request['charge'] = xxx;
```

Am I missing something here?

**Comment by roykho** [comment]
Ah its only available in charge requests.

**Comment by msaggiorato** [comment]
I truly believe that adding a filter won't make any problems, and there won't be no need to remove it in the future. This type of filtering might be very useful to some edge case implementations, and is something that's not likely to change (data being filtered might change, but the filter itself, a request made to stripe for refunding, will always be there).

**Comment by roykho** [comment]
@msaggiorato added the filter here in case you still need it https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L744

**Pull request closed without merging**
