### PR TITLE
Pass customer language/locale to Stripe upon creation or modification.

### LINKED ISSUE #744: Allow for different language SEPA emails
#### Affected ticket(s)

1465055-zen

#### Problem

SEPA emails are sent out in English, regardless of the site's language: 

```
Single Euro Payments Area

We're writing you to let you know that your purchase from [site name] for €1.10 will be debited from [bank account] within 2 days.

This transaction will appear on your bank statement as "[site name]", with mandate reference [reference] and creditor identifier [identifier]. 
You can reach out to [site name] with any questions. If you do not recognize this purchase, please respond to this email. 
Note: You are receiving this message from Stripe because [site name] uses Stripe to process payments online (https://stripe.com). 
..."
```

I know this has been raised multiple times before, and I had understood that Stripe's API didn't offer an option to adjust the language. 

This customer reached out to Stripe and let them know the following: 

> its available in the api To change this, a URL to view the mandate is returned as the value for sepa_debit[mandate_url]​ and the details are generated as part of the Source object creation[1]. So you would just need to change the URL to match the German text instead of the English one.

This is important for all of our international customers. Is this something we can implement?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by jessepearson**
# Changes proposed in this Pull Request:

Issue: 
Fixes #744

Description: 
When a customer is either created or modified the `generate_customer_request` method is called. Within that, I added a call to the new method `get_customer_preferred_locale` that gets the customer locale based on the user or site settings. If the user/site locale does not match [one of the supported Stripe locales](https://support.stripe.com/questions/language-options-for-customer-emails), an empty array is returned.

# Testing instructions

Testing instructions: How should this be tested and how can a reviewer test the end-user functionality? Are there known issues that you plan to address in a future PR? Are there any side effects that readers should be aware of?

1. Set your user or site language to [one of the supported Stripe languages](https://support.stripe.com/questions/language-options-for-customer-emails)
2. Make a purchase.
3. Check the purchase, and then the customer in Stripe.
4. The customer's Language under Details should be the language set for your user/site. 

Markup 2021-03-31 at 13 30 52

# Notes
I was going to make tests for this, but since this relies on functions and not methods it was difficult to attempt to mock without getting complicated. An alternate testing route would have been to set up `get_customer_locale` to return set values, but that would basically be handing the expected return to the test. If there are any ideas on this, I am willing to work on them.

### CODE REVIEW

**Comment by boboz** [comment]
Did a buy with Stripe in test-mode. The language was set and the receipt generated in the expected language. Heading still in English though but is perhaps a Stripe-issue?
Thank you for working on this!

**Comment by jessepearson** [comment]
@boboz What email was it? Do you have a screenshot? I didn't get any emails myself due to my Stripe account not being live, but when I try to send out an invoice, the email is fully in the language specified:


Image Link: https://d.pr/i/9fAhaN

Also, just pushed a small update. I hadn't tested in a language that wasn't supported, and it seems Stripe isn't happy if you include an empty array if `preferred_locales` is included with the customer request.

**Review by diegocurbelo — APPROVED** [review]
LGTM :shipit: 

Tested with a couple of languages and works as expected. Also the email's subject is in the correct language:

Screen Shot 2021-04-09 at 16 56 50

@jessepearson Can you fix the readme and changeling conflicts?

**Comment by jessepearson** [comment]
> Can you fix the readme and changeling conflicts?

@diegocurbelo Done. Not sure of the team's process for merging, so I haven't done that yet.

**Comment by diegocurbelo** [comment]
> > Can you fix the readme and changeling conflicts?
> 
> @diegocurbelo Done. Not sure of the team's process for merging, so I haven't done that yet.

After the reviewer adds the `pr: ready to merge` label, the author just merge it into trunk... 🚢 🚢

**Pull request merged**
