### PR TITLE
Add to disallowed descriptor character list

### LINKED ISSUE #1262: clean_statement_descriptor needs to be extended by /, (, ), {, and }
Has PR #1263 

**Describe the bug**
wp-content\plugins\woocommerce-gateway-stripe\includes\class-wc-stripe-helper.php
public static function clean_statement_descriptor( $statement_descriptor = '' )

**To Reproduce**
Use "WOO {123}" as statement descriptor

**Expected behavior**
"{" and "}" should be stripped.

**Environment (please complete the following information):**
 - WordPress Version: 5.4.2
 - WooCommerce Version: 4.3.1
 - Stripe Plugin Version: 4.5.0

**Additional context**
```
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [code] => invalid_statement_descriptor
            [message] => Invalid statement descriptor. Cannot contain the characters /, (, ), {, or }
            [param] => sofort[statement_descriptor]
            [type] => invalid_request_error
        )

)
```

### PR DESCRIPTION
**Pull request by allendav**
Fixes #1262 .

#### Changes proposed in this Pull Request:
- Adds / ( ) { and } to disallowed descriptor character list

#### Testing
- Attempt to add those characters to your descriptor. Ensure they are removed for you.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Review by luizreis — CHANGES_REQUESTED** [review]
I took the liberty of updating the tests in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1263/commits/ec644dafbc311669dbcb14527e78c9d62f22b6c0 and updating the tooltip in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1263/commits/e9510eff32fa3614b8e0f2c7da765da804c2c507. What do you think of those changes?

I noticed that the tooltip also mentions `\` and `*` as disallowed characters, but they're not in the `clean_statement_descriptor` list. Should we add them?

**Comment by v18** [comment]
Hey @allendav - would you be able to take a look at this PR and update it based on @luizreis's comment above?

**Comment by allendav** [comment]
Hey @v18 - yup - can do - will take care of this tomorrow

**Comment by allendav** [comment]
@v18 @luizreis - this is ready for review again. I also noticed that we weren't removing the disallowed characters from the settings when saving changes so I added a filter to do that too.

**Review by luizreis — COMMENTED** [review]
@allendav - Thanks for addressing those issues! I've also submitted a commit to fix a wrong indentation I introduced on the tests refactor.

---

I found a bug while testing this when using `<` and `>`, or any character that is converted to an HTML entity as part of the input sanitization. Basically, those characters are not stripped from the string as instead of being represented by the `<` or `>` chars, they're represented with `&lt;` and `&gt;`.

This could lead to some strange issues, such as a `<` on the 22nd position resulting in an `&`. E.g. `aaaaaaaaaaaaaaaaaaaaa<` becomes `aaaaaaaaaaaaaaaaaaaaa&` after saving the changes.

Do you feel like we should fix this bug as part of this PR? Or should we create a new issue?

**Comment by allendav** [comment]
I'll strip those too. Will post an update today.

**Review by luizreis — APPROVED** [review]
@allendav - looks good! I don't want to block this too much, so I'm approving it with the following caveat: some other allowed characters that are converted to HTML entities might be removed from the string, such as `& (&amp;)`. That happens because they're not being converted from the HTML entity to the actual character and end up being removed by the `preg_replace` that removes any entities. E.g. `A & B` becomes `A  B`.

**Comment by allendav** [comment]
> some other allowed characters that are converted to HTML entities might be removed from the string

My intention exactly. Descriptors really only need to support letters and numbers and spaces at the end of the day. Anything else can lead to trouble imho.

**Pull request merged**
