### PR TITLE
Prevent duplicate customer creation during guest checkout

### LINKED ISSUE #3124: Duplicate customers created on guest checkout
**Describe the bug**
If you place an order as a guest, it doesn’t associate the purchases with an existing Stripe customer. Instead, it creates a new customer.

I found an old report (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1079) with similar behaviour with failed payment. But this time, it occurs after successful payment and order. However, it works fine for logged-in users or those with an account on the site.

**To Reproduce**
1. Enable guest checkout in WooCommerce.
2. Place multiple orders using the same name, billing address and email. (without creating an account)
3. Check payments and customers in the Stripe Dashboard

**Expected behavior**

If there is a Stripe customer, the purchase should be associated with the existing customer instead of creating a new customer.

**Screenshots**
CleanShot 2024-05-07 at 09 00 15

CleanShot 2024-05-07 at 09 00 54

CleanShot 2024-05-07 at 09 01 43

**Environment (please complete the following information):**
 - WordPress Version: 6.5.2
 - WooCommerce Version: 8.8.3
 - Stripe Plugin Version: 8.2.0 
 - Browser and Version: Safari, Chrome, and Firefox Latest.

**Additional context**
Reported here: 8151786-zen
Thread: https://wordpress.org/support/topic/duplicate-customers/

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3124

If you place an order as a guest, it doesn’t associate the purchases with an existing Stripe customer. Instead, it creates a new customer.

This PR fixes the issue by searching for an existing customer in Stripe before creating a new customer for guest checkouts.

This PR depends on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2980. The current version of Stripe (`'2019-09-09'`) does not support the search API. So for the changes in this PR to work we have to update the Stripe API version first which is addressed in the [mentioned PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2980).

## Changes proposed in this Pull Request:
- Using the customer search API to look up the customer with email and name.
- Before creating a customer in Stripe for a guest user, we are now checking if a customer already exists in the Stripe end for this email and name. If exists, we won't create a new customer.

#### Reproduce the issue for guest checkout
1. Checkout to the `develop` branch.
2. As a guest user, add a product to the cart and go to the checkout page.
3. Fill up the details, and use a new email on the checkout form. (i.e, `tom.cat@example.com`)
4. Complete the checkout with the card payment method. 
5. Go to your stripe dashboard and confirm a new user has been created.
6. Now as a guest user, again add a product to the cart and complete the checkout using the same details used in the previous checkout (`tom.cat@example.com`)  
7. Go to your stripe dashboard again and confirm that a second user has been created with the same email.

#### Test for guest checkout
1. Checkout to the `fix/3124-duplicate-customer` branch.
2.  In `includes/class-wc-stripe-api.php` update the `STRIPE_API_VERSION` to `'2023-10-16'`
3. As a guest user, add a product to the cart and go to the checkout page.
4. Fill up the details, and use a new email on the checkout form. (i.e, `jerry.mouse@example.com`)
5. Complete the checkout with the card payment method. 
6. Go to your stripe dashboard and confirm a new user has been created.
7. Now as a guest user, again add a product to the cart and complete the checkout using the same details used in the previous checkout (`jerry.mouse@example.com`)  
8. Go to your stripe dashboard again and confirm that no new user has been created with the same email.
9. In the Stripe dashboard, click the customer and go to the customer details page. Confirm that 2 payments are linked to this customer.

#### Test for logged in user 
No changes has been made related to logged in user, so it should keep working as before.
1. Checkout to the `fix/3124-duplicate-customer` branch.
2. In `includes/class-wc-stripe-api.php` update the `STRIPE_API_VERSION` to `'2023-10-16'`
3. Log in to the store as an existing user and add a product to your cart.
4. Complete the checkout with the card payment method for this logged in user.
5. Go to your stripe dashboard and confirm no new user has been created.
6. In the Stripe dashboard, find the customer and go to the customer details page. Confirm that the above transaction is listed in the payments section of the corresponding customer.

### CODE REVIEW

**Review by mattallan — COMMENTED** [review]
Nice changes @Mayisha !!

- [x] Confirmed issue on `develop`
- [x] Confirmed purchasing as guest with an existing Stripe account doesn't create a new Stripe Customer
- [x] Confirmed purchasing as a guest without a Stripe account does create a new Stripe Customer
- [x] Confirmed purchased while logged in with existing account doesn't create a new customer
- [x] Ran above tests with non-UPE and UPE enabled.

---

I have a couple of follow-up questions from my review:
1. Should we update the billing address in Stripe if existing customer is found?
   - While I was testing this PR, I noticed that when **UPE is disabled**, checking out as Guest with an email that belonged to an existing stripe customer was updating the billing address on the customer. But when I ran the same test with UPE enabled, the existing customer's billing address wasn't being updated.
   - This might not be related to this PR but I was wondering if we should also be calling `update_customer()` if `get_existing_customer()` returns a valid customer.
2. Should we add a Stripe API version check?
  - Before calling `get_existing_customer()` should we also check `WC_Stripe_API::STRIPE_API_VERSION`? Or should we put this PR on hold until https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2980 is merged?

**Comment by lkraav** [comment]
It's unclear why #2980 is stalled since March, anyone here know?

**Comment by Mayisha** [comment]
Regarding the follow-up questions-

> Should we update the billing address in Stripe if existing customer is found?

Addressed it in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3149/commits/e9da1bdde26249e5073f3b0ca54a4c14a697c794

> Should we add a Stripe API version check?

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2980 is already merged, so we don't need to add any API version check.

**Review by diegocurbelo — APPROVED** [review]
The code looks good, and it tests well 🚢 .

As specified in the PR details, all 3 fields (first name, last name, and email) need to match for the customer to be re-used; if any of them is different a new user is created:
Screenshot 2024-07-10 at 12 30 24 AM

**Pull request merged**
