### PR TITLE
Implement Stripe Express Checkout Elements (ECE) on the Product page

### LINKED ISSUE #3410: [ECE] Implement ECE for payment processing on product page
### Description
Display the ECE button and process payment with the button on the product page.

### Acceptance Criteria
- ECE buttons are rendered on the product page.
- You can successfully process payment with the ECE button from the product page.
- Both success and failure cases are handled including necessary notices.
- ECE implementation should support all the product types supported by PRB.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #3410 

> [!IMPORTANT]
> This PR is based off the changes in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436. This branch will need to be updated to include any future changes made to that base branch.

## Changes proposed in this Pull Request:

This PR implements Stripe's ECE (Google Pay & Apple Pay buttons) on the product page:

| Chrome | Safari |
|--------|--------|
| image | image |

## Testing instructions

There are **A LOT** scenarios to cover when testing these buttons from the product page. Let's start with the basics:

1. Enable the ECE feature flag in the wp-options table. 
```
update_option( '_wcstripe_feature_ece', 'yes' );
```
2. Make sure Apple Pay and Google Pay are enabled: 
image
3. Create a simple WC Product and visit the front-facing Product page
4. Change the quantity of the product, confirm the ECE button was blocked and unblocked
5. Click on the Google Pay button
6. Confirm the order details and totals in Google Pay are correct
7. Change shipping methods between free and flat rate and confirm price is correct

| Free | Flat rate |
|--------|--------|
| image | image| 
8. Complete the google pay purchase
9. Confirm the order is created in WooCommerce
10. Confirm the charge in Stripe is correct
image

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Comment by mattallan** [comment]
**Full checklist I'm testing**

- [x] Simple product
- [x] Variable product
- [x] Set quantity to 2 or 3 (confirm element is blocked and unblocked)
- [x] Bookings product
- [x] Simple subscription
- [x] Variable subscription
- [x] Synced subscription with no initial payment
- [x] Simple product with deposit
- [x] Variable product with deposit
- [x] Simple subscription with deposit
- [x] Variable subscription with deposit
- [x] Virtual/downloadable product
- [x] Virtual subscription
- [x] Store without taxes
- [x] Store with taxes
    - [x] Prices include tax - tax applies
    - [x] Prices include tax - outside of taxable region
    - [x] Prices exclusive of tax

**Non-successful test cases**
- [ ] Error notices when using a declining card
- [x] Abort/cancel ECE window and re-open
- [x] Use an invalid shipping address

**Comment by wjrosa** [comment]
Hey Matt! I see the changelog.txt entry is missing 👀

**Review by wjrosa — APPROVED** [review]
Awesome work, Matt!

> 4. Change the quantity of the product, confirm the ECE button was blocked and unblocked

Screenshot 2024-09-30 at 09 06 16
(tried to get a blocked image, but the loading is too fast)

> 6. Confirm the order details and totals in Google Pay are correct

Screenshot 2024-09-30 at 09 09 12

> 7. Change shipping methods between free and flat rate and confirm price is correct

Screenshot 2024-09-30 at 09 15 48

> 9. Confirm the order is created in WooCommerce

Screenshot 2024-09-30 at 09 19 24

> 10. Confirm the charge in Stripe is correct

Screenshot 2024-09-30 at 09 21 26

It does not work on my Android phone, but none of our previous implementations for this project does. We need to double check later.

**Comment by mattallan** [comment]
Thanks @wjrosa for the review!
I've pushed up [fea0f12](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3441/commits/fea0f126e8d865a2faab82d44a0c4d4a874da371) to add the changelog entry back in

**Pull request merged**
