### PR TITLE
Fix 'No such customer' error in new checkout experience 

### LINKED ISSUE #3109: 'No such customer' error in new checkout experience
Reported in 8084002-zd-a8c

Unable to place test orders after enabling the new checkout experience. The following error occurs in the checkout

`There was an error processing the payment: No such customer: '[Stripe customer ID]'; a similar object exists in live mode, but a test mode key was used to make this request.`

This happens when user tries to checkout with an email that had been previously used in live mode. The error does not occur in the legacy checkout experience.

**To Reproduce**
1. Enable the new checkout experience.
2. Enable test mode.
3. As a shopper try to place an order using an email that has a corresponding customer in Stripe live mode (you may need to manually create the live mode customer in Stripe)
4. You should see the following error

notice

**Expected behavior**
In the legacy experience, a new test mode customer is recreated in Stripe in this scenario. The same should happen in the new checkout experience as well and you should be able to place an order successfully.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3109 

Unable to place test orders after enabling the new checkout experience. The following error occurs in the checkout

notice

This happens when the user tries to checkout with an email that had been previously used in live mode. The error does not occur in the legacy checkout experience.

## Changes proposed in this Pull Request:
With UPE enabled when we get this 'No such customer' error from Stripe, we delete the customer ID from the user meta and order meta. However, in the retry request, we still send the same customer ID. For this, all 5 retry requests fail and we get the error notice on the checkout page.

When legacy checkout is enabled (non-UPE), after deleting the customer ID we make the retry request with a recreated customer ID. So the payment gets successful on the 2nd retry request. 

In this PR, we are doing the same for UPE.

## Testing instructions

1. Go to your Stripe settings page and uncheck the `Enable the legacy checkout experience` checkbox (enable UPE).
2. Enable test mode from your Stripe settings page.
3. In your `wp-admin` create a new user (`donald.duck@test.com`).
4. Go to your Stripe dashboard's customer page (https://dashboard.stripe.com/customers) and create a new customer with the same email (`donald.duck@test.com`).
5. From your database, find the user ID for this newly created user. From Stripe dashboard find the customer ID from URL.
6. Now in the `wp_usermeta` table of your DB add a new row where the `user_id` is your new user's id, `meta_key` is `wp__stripe_customer_id` and `meta_value` is the customer id from Stripe dashboard.
7. As a shopper try to place an order using the above email id (`donald.duck@test.com`).
8. In `develop` branch you should get the mentioned error.

`There was an error processing the payment: No such customer: '[Stripe customer ID]'; a similar object exists in live mode, but a test mode key was used to make this request.`

9. In this branch, the checkout should be successful. In your Stripe dashboard, a new customer should be created in the test mode with the above email id.

### CODE REVIEW

**Comment by mriyazuddin** [comment]
- [ ] #8084002-zd

**Review by james-allan — APPROVED** [review]
I cannot overstate how personally thankful I am of this change!

As you mentioned, this impacts legitimate stores where users complete purchases in different test or live modes. This also fixes this error for stores that change accounts frequently like we do while testing different merchant account setups.

The changes look good and tested well for me. I used the account changing method for testing I tried to confirm the method you outlined in the PR description, however I don't have access to a Stripe Account that can go into live mode in order to create an customer account in live mode. I created an customer account for Donald.Duck 🦆 in test mode but that was, as expected, accepted. 

I verified subscriptions isn't impacted by this change in any way because it doesn't go through this flow. Deleting and recreating the customer in a subscription situation wouldn't be helpful anyway.

**Comment by EdithAllison** [comment]
Thank you! I've been scratching my head why we've suddenly got this error. Do you know when this fix will be released?

**Comment by james-allan** [comment]
@EdithAllison this fix is currently planned for the next version of the plugin which is slated for June 13th.

**Pull request merged**
