### PR TITLE
Setup the e2e tests environment using WC e2e boilerplate

### PR DESCRIPTION
**Pull request by a-danae**
Set up the e2e tests environment with the updated tools that Core and WC Payments use.

No related issue. I can create one if needed.

The current scripts for running the e2e tests were failing. After checking in with the team that handled it, we agreed that it'd be better to set up the e2e tests with more updated tools instead of trying to fix the previous approach. There are more details behind that decision in pdkmC9-6x-p2

## Changes proposed in this Pull Request:

* Setting up [WC's e2e boilerplate](https://github.com/woocommerce/woocommerce-e2e-boilerplate)
* Removing the existing e2e tests, although we might re-add them next with the current tools
* Adding the base files and dependencies for running the example test
* Adding a base file for flows to be used across tests

## Testing instructions

**Testing the basic setup**
- Run `npm i` if it doesn't run automatically when checking this branch out
- Run `npm run test:e2e-up`
- The test site should be accessible at this point at http://localhost:8084/wp-admin/ , admin:password. You'd also find its container in your Docker
- WooCommerce should be installed and active
- WooCommerce Stripe Gateway should be installed

- Run `npm run test:e2e`
- One test should be run and it should pass with no warnings nor errors

**Testing the dev and debug setups**
- Run `npm run test:e2e-dev`
- One test should be run and it should pass with no warnings nor errors

- Run `npm run test:e2e-debug`
- The example test should be run and it should pass with no warnings nor errors

**Testing the ssh access**
- Run `npm run test:e2e-ssh`
- You should have accessed the container via ssh with no errors
- Exit the ssh access

**Testing taking the container down**
- Run `npm run test:e2e-down`
- The site shouldn't be accessible anymore at http://localhost:8084/
- The container shouldn't be up in Docker

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by a-danae** [comment]
@chickenn00dle  I've been checking out why the tests fail in this PR while they run fine on `develop`. For the JS linting ones, looks like the package `@automattic/puppeteer-utils` [locks the Eslint ](https://github.com/Automattic/puppeteer-utils/blob/master/package.json#L23)version to 6.7.2 and support for the optional chaining we're getting the errors for was introduced in [7.5.0](https://eslint.org/blog/2020/07/eslint-v7.5.0-released).

The installed Eslint version in the node modules is 6.7.2 when`@woocommerce/e2e-environment` is included (which has `@automattic/puppeteer-utils` [as a dependency](https://www.npmjs.com/package/@woocommerce/e2e-environment?activeTab=dependencies)), while it's 7.32.0 when it's not included. 

I'm checking out the JS unit tests next, but not sure which way to go for this linting one. We could simply use `eslint-disable-next-line no-unused-expressions` to silence the errors, or we could change the optional chaining to a classic `if(){}`, although the latter one feels like a step backward. Ideally, we'd update the version in that package to a more recent one, but I guess that'd take longer. What do you think?

**Comment by chickenn00dle** [comment]
Hey @a-danae, I hadn't started looking into this one yet as I was planning to do the review later this evening, but based on a quick look, I think the simplest solution, for now, is to simply rewrite the problematic code so that it is no longer using optional chaining.

I'll wait for you to resolve the unit tests before I start my review.

**Comment by a-danae** [comment]
@chickenn00dle The issue seems to be that the `speak` function from `@wordpress/a11y` isn't being mocked [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2238/files#diff-f558a2bb1e6e3625f54d34e9b1225700a2c13a2b851220dad69fea4cf6298a70L7) after introducing `@woocommerce/e2e-environment`. If you comment out that mock in `develop` you'll get the same failures we're getting on this branch.

The `speak` function [prints the notice for screen readers](https://github.com/WordPress/gutenberg/blob/7cbba2646a522738fd95894db8240e4d3d5ac1d3/packages/a11y/src/index.js#L60), so we have the message twice in the page when Stripe isn't available (we use the [Notice](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/notice/index.js#L35) component to display the message). All good so far.

Because `speak` was mocked before, we're not expecting the screen reader version of this message in the tests we're getting printed now, thus they fail. Now, I'm not sure why it's not being mocked now. I see the `@wordpress/a11y` was downgraded after introducing `@woocoommerce/e2e-environment`, but I didn't find a reason why this would affect these tests.

The tests run fine for me locally after making the mock virtual in [0af0c20](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2238/commits/0af0c20153ada330334e017fcb6116d921cb0e52), but they keep failing here. Do they work locally for you, Raz?

**Comment by chickenn00dle** [comment]
Hey @a-danae,

> The tests run fine for me locally after making the mock virtual in 0af0c20, but they keep failing here. Do they work locally for you, Raz?

It looks like the tests are running fine for me locally. I'm not entirely sure what the problem might be, but I wonder if the problem has something to do with the call to `clearAllMocks` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3865f6f9ea332f1542423f88a5b3e6e49c90e87a/client/entrypoints/payment-request-settings/__tests__/payment-request-button-preview.test.js#L45-L47)?

I ran into a similar sort of problem when trying to mock a different WP package a while back where clearing all mocks seemed to break tests that relied on this mock. Perhaps we can try explicitly clearing individual mocks here instead?

**Comment by chickenn00dle** [comment]
Hey @a-danae, I've unassigned and removed myself as reviewer from this PR as I'll be AFK starting tomorrow and don't want to hold this one up.

**Comment by a-danae** [comment]
Thanks for checking this out @chickenn00dle!

> but I wonder if the problem has something to do with the call to clearAllMocks here?

I tried explicitly clearing the mocks, removing clearAllMocks, and a some other things, but no luck. I pushed some of them with their reverts for you to check.

We could adjust the tests, but I'm reluctant about doing so because the functionality it tests didn't change. Also, I think it'd be good to keep this test consistent with the one from WCPay [here](https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/payment-method-settings/test/payment-request-button-preview.test.js).

Mocking `@wordpress/a11y`'s speak function again should be enough, but I'm missing something for that to work. The `virtual` option from [0af0c20](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/0af0c20153ada330334e017fcb6116d921cb0e52) working locally but not in here is confusing. I'll ping around for help.

**Comment by a-danae** [comment]
After some debugging and Diego's help, turned out that the problem with the tests also happens to develop branch when you do some steps. I've created a [separate issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2265) for that and built things on top of the package-lock.json file from develop. This is ready to review.

**Review by chickenn00dle — APPROVED** [review]
Nice work getting to the bottom of those failing tests @a-danae 👍 

I just tested the e2e test suite and it works as expected.

This should be good to go after resolving conflicts.

**Comment by a-danae** [comment]
@chickenn00dle I've solved the conflicts in `package.json` but now some PHP tests are failing. They all pass locally, and they don't seem to be related to the changes from the last commit. I ran the GH action some hours after they failed for the first time in case it was something temporary but they still fail. I was thinking of asking in the Stripe channel about this, but what do you think?

**Comment by chickenn00dle** [comment]
> I was thinking of asking in the Stripe channel about this, but what do you think?

Yup. This sounds like a good idea as they might have a good idea if tests are meant to not be passing right now.

Considering you haven't made changes to any PHP files, I suspect a different PR might be causing the problem here.

**Comment by leonardola** [comment]
The failing tests seem to be related to #2302. We'll wait until it is merged in develop to see if tests pass after that.

**Pull request merged**
