### PR TITLE
Don't update order status on review closed if capture is disabled

### LINKED ISSUE #1583: Uncaptured Payment Cancelled Bug for Dashboard Review Approval
Hello

I think there is a very annoying bug with this plugin that will cause preauthorized payments get lost.

If you have manual capture set and payment goes to radar review. This payment will normally be set to On-Hold. Till now everything is fine but things starts to get funny when you approve the open review of the uncaptured payment from the stripe dashboard. Woocommerce will change order to pending payment.
`The opened review for this order is now closed. Reason: (approved) Order status changed from On hold to Pending payment.`

After a few hours this payment will be marked as cancelled automatically by woocommerce and it will send API request to Stripe to cancel the uncaptured payment.
`Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.`

I believe this should be changed. Payment under review that get approved from Stripe dashboard should not change the status of the order.

I stopped approving the review from the stripe dashboard because of this.

Thank you

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #1583

## Changes proposed in this Pull Request:

This PR changes the behavior of updating the status of an order upon closing a review entry over the Stripe dashboard (when using the Radar feature). Currently, all orders approved/rejected have their status updated accordingly. But this ignores the automatic capture setting.

Now, when automatic capture is disabled, only the review note will be added and the status will remain as is.

The original bug is hard to reproduce because an uncaptured order will have the `on-hold` status, as will an order under review. When the review closed webhook triggers, it should try to update the order status to the previous value (also `on-hold`), and nothing should change (except for the order note).

That being said, this fix here is more of an additional measure to avoid similar bugs.

## Testing instructions

As mentioned above, it is hard to test the specific scenario reported in the issue, but you can try:

- Checkout and build this branch on your test site (`fix/dont-update-order-status-on-review-closed-if-capture-disabled`)
- Connect your test Stripe account
- Enable manual capture on `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings` ("Issue an authorization on checkout, and capture later")
- On your Stripe dashboard, create a generic rule to force a transaction to fall into the review queue
-- Go to `/settings/radar/rules`
-- Click "+ Add rule" on the top
-- Select "Add manual review rule..."
-- Add the condition like `::card_brand:: = 'visa'`. Or anything similar that makes it easier to match a payment. You can see some valid fields [here](https://docs.stripe.com/radar/rules/supported-attributes#card-info)
- As a shopper, purchase any product using a method that should match the rule you created. In the example above, you try to use the `4242424242424242` card
- The order should be put on hold and appear on your Radar review list over the Stripe dashboard (`/radar/reviews`)
- Approving the transaction should not change its status on your test store

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Review by mattallan — CHANGES_REQUESTED** [review]
Hey @wjrosa with these changes, it means that we're only updating the status of the order on `review.close` if manual capture is disabled in the settings which I don't think will work in all cases.

i.e. What happens if a merchant disables manual capture and then approves a review for order that was already captured previously. The status will no longer be updated on the `review.closed` webhook.

Instead of adding `$this->is_automatic_capture_enabled()` to the condition in `process_review_closed()`, would it fix things if we moved the `'yes' === $order->get_meta( '_stripe_charge_captured' )` [that's already here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-webhook-handler.php#L812C9-L812C64) to the outer if condition [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3c6eb4b08e1725d4921c35ff7e24e565f8dd0440/includes/class-wc-stripe-webhook-handler.php#L803-L808).

This would mean if the order hasn't been captured yet, we'll add an order note to say it has been reviewed, and won't update the status of the order.

I'd like to understand what is happening here because I thought the existing `'yes' === $order->get_meta( '_stripe_charge_captured' )` would be preventing the `$status_after_review` to be set to `'processing'` 🤔 Maybe this issue is being caused by some orders missing the `_stripe_status_before_hold` meta which causes `get_stripe_order_status_before_hold()` to return the default status which is 'processing'.

**Comment by wjrosa** [comment]
> Hey @wjrosa with these changes, it means that we're only updating the status of the order on `review.close` if manual capture is disabled in the settings which I don't think will work in all cases.
> 
> i.e. What happens if a merchant disables manual capture and then approves a review for order that was already captured previously. The status will no longer be updated on the `review.closed` webhook.
> 
> Instead of adding `$this->is_automatic_capture_enabled()` to the condition in `process_review_closed()`, would it fix things if we moved the `'yes' === $order->get_meta( '_stripe_charge_captured' )` [that's already here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-webhook-handler.php#L812C9-L812C64) to the outer if condition [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3c6eb4b08e1725d4921c35ff7e24e565f8dd0440/includes/class-wc-stripe-webhook-handler.php#L803-L808).
> 
> This would mean if the order hasn't been captured yet, we'll add an order note to say it has been reviewed, and won't update the status of the order.
> 
> I'd like to understand what is happening here because I thought the existing `'yes' === $order->get_meta( '_stripe_charge_captured' )` would be preventing the `$status_after_review` to be set to `'processing'` 🤔 Maybe this issue is being caused by some orders missing the `_stripe_status_before_hold` meta which causes `get_stripe_order_status_before_hold()` to return the default status which is 'processing'.

Hi @mattallan ! That's a great observation and suggestion! It makes total sense and solves the merchant issue. I have implemented it on my latest commits.

Yeah, it is hard to understand what is really happening for this merchant, but I think your idea might prevent the bug while keeping the expected behavior in place.

**Review by mattallan — APPROVED** [review]
Thanks @wjrosa !!

I've tested the following:

- [x] Uncaptured order in review. Approving the transaction now adds an order note to say it's been approved but the status doesn't change.
- [x] ❓ Uncaptured order in review. Capturing the transaction before approving it.
   - I'm not actually sure what's supposed to happen in this case. On stripe the transaction is still in review and needs approval but capturing it updates it in Woo to processing 🤔 Maybe this is the original issue?
   - This issue isn't introduced by this PR so I'm happy if we want to fix this separately.
- [x] Automatically captured order in review. Approving the transaction transitions it from on-hold to processing.

**Comment by wjrosa** [comment]
Thanks for testing all these steps, Matt!

> I'm not actually sure what's supposed to happen in this case.

Hum, if we had some condition like "order is under review" (or a way to build it), we could check that inside the capture block and avoid changing the status there.

Edit: what if we add a new meta to the order when `process_review_opened` is called for this?

**Pull request merged**
