### PR TITLE
Add connection token API

### LINKED ISSUE #2123: Add API endpoint to fetch connection token
**Description**

For in-person payments, the mobile application will need to call an endpoint to get a new connection token used by Stripe Terminal SDK to connect to a card reader.

Sample response:

```
{
  "data" : {
    "secret": "abcdef",
    "test_mode": true
  }
}
```

**Additional context**

pdfdoF-er-p2

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #2123

## Changes proposed in this Pull Request:

This PR adds an API endpoint (`/wp-json/wc/v3/wc_stripe/connection_tokens`) for connection tokens, for use by mobile apps. For the mobile app to connect to a card reader, the Stripe extension needs to [request a connection token object](https://stripe.com/docs/api/terminal/connection_tokens) and send it back to the mobile app.

## Testing instructions

Below is a test plugin that can be added to your site to test the new API endpoint, adapted from a [similar test plugin](https://github.com/Automattic/woocommerce-payments/pull/1283) from when WCPay implemented this same endpoint.

```php
<?php
/*
Plugin Name: Stripe Connection Token Test
*/

function stripe_connection_token_test() {
?>
    <div class="notice">
		<span id="test">Loading...</span>
		<script>
			document.addEventListener( 'DOMContentLoaded', function() {
				fetch( '/wp-json/wc/v3/wc_stripe/connection_tokens', {
					method: 'POST',
					headers: { 'X-WP-Nonce': wpApiSettings.nonce },
				} )
				.then( response => response.json() )
				.then( data => {
					document.querySelector('#test').innerHTML = JSON.stringify( data );
				} )
				.catch( error => {
					document.querySelector('#test').innerHTML = 'Error: ' + error;
				} );
			} );
		</script>
	</div>
<?php
}

add_action( 'admin_notices', 'stripe_connection_token_test' );
```

1. Activate Stripe extension, add Stripe API credentials to settings.
2. Activate the above test plugin.
3. Visit any admin page.
4. Verify that you can see a connection token generated by Stripe.
5. Verify that the structure of the JSON data returned matches the sample response under "Fetch Connection Token" in pdfdoF-er-p2.
6. Remove Stripe API credentials from settings.
7. Verify that the API returns an error indicating that Stripe did not return a connection token.

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Nice work @brianyu28 🙌 

I tested and for the most part this looks good. There is just one issue with the response format. I am seeing the following when I request connection tokens via this endpoint:

```
{
    "object": "terminal.connection_token",
    "secret": "pst_test_YWNjdF8xRXhSdEdMSXA3ZU5oTXBELHdRZnVuak12TVBTY0Zab1RrcXdQcjkzdUprU1dzbjg_00pdc1Pu3Z",
    "test_mode": true
}
```

But it looks like we are wanting a specific format per the P2 link you provided in this PR:

```
{
  "data" : {
    "secret": "abcdef",
    "test_mode": true
  }
}
```

I wasn't sure how firm we were on this format, but if this is something we are wanting to stick to, we'll need to format the response in `create_token`

**Comment by leonardola** [comment]
@brianyu28 

This is the response present in pdfdoF-er-p2 
```
{
  "data" : {
    "secret": "abcdef",
    "test_mode": true
  }
}
```

This is the response I am getting:
```
{
	"object":"terminal.connection_token",
        "secret":"pst_test_YWNjdF8xSnI4Z1NJQnpOc2Z2Q2hQLG5...",
	"test_mode":true
}
```

Shouldn't it be?:
```
{
    "data": {
	"object":"terminal.connection_token",
        "secret":"pst_test_YWNjdF8xSnI4Z1NJQnpOc2Z2Q2hQLG5...",
	"test_mode":true
    }
}
```

Should the endpoint still work when all stripe methods are disabled?

Other than that it LGTM

**Comment by brianyu28** [comment]
Thanks, @leonardola and @chickenn00dle — I originally had the response JSON wrapped in a `data` key, but then I removed it after testing the same endpoint on WCPay and realizing WCPay doesn't put the results in the `data` key. I'll check with the mobile team and see what they're expecting, and then I'll follow up here.

**Comment by brianyu28** [comment]
To follow up on this, the mobile team is calling the endpoints on the WP.com REST API, which proxies the request to a Jetpack site. It looks like that proxying is where the `data` key gets added, so we don't need the `data` key in the extension.

**Review by leonardola — APPROVED** [review]

**Comment by brianyu28** [comment]
Thanks, @leonardola! I'll merge it if it looks good to @chickenn00dle too?

**Review by chickenn00dle — APPROVED** [review]

**Comment by chickenn00dle** [comment]
Sorry for the delay. Thanks for confirming @brianyu28. This is good to go then 🚢

**Pull request merged**
