### PR TITLE
Fix duplicate intent actions when webhooks are enabled.

### LINKED ISSUE #889: Duplicate processing notes/duplicate emails around payment intent related webhooks
#### Affected ticket(s)

2094750-zen

#### Description

From @WillBrubaker 👍 

> I have checked it also in a staging system and the error still occurs there. Now I have take a look at the source code of the plugin and think I found the problem:

>In the file includes/class-wc-stripe-webhook-handler.php (on line 604) the method process_payment_intent_success has been added. This method is called by the Stripe webhook on the payment_intent.succeeded notification (see line 692).

> The method process_payment_intent_success only returns in case of order status "pending" or "failed" (line 619). Otherwise the method process_response will be called. At this point, however, process_response has already been called by the regular payment processing and the order has already the status "completed" when called via the webhook.

> On line 619 there should also be a return in order of order status "completed" or (I think) "on-hold". Or - I’m not sure - the notification payment_intent.succeeded should be completely ignored like in the previous versions of the plugin.

> If you test it on your system, make sure that payment_intent.succeeded is activated on the Stripe webhook detail panel:

E3a7e_yg

> After completing the payment you should see the notification on the Stripe webhook log:

XLZeS3fA

Possibly related: #882

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #889

#### Changes proposed in this Pull Request:

`WC_Gateway_Stripe::verify_intent_after_checkout` (called during the redirect from Checkout to Thank You) contains something like this:

```php
if ( 'pending' !== $order->get_status() && 'failed' !== $order->get_status() ) {
	// If payment has already been completed, this function is redundant.
	return;
}

$intent = $this->get_intent_from_order( $order ); // A slow function, because of remote calls

if ( $this->lock_order_payment( $order, $intent ) ) {
	// Do not proceed if the order is being handled by a webhook at the moment.
	return;
}
```

The locking mechanism works fine __if__ this method gets entered __while__ a webhook is handling the intent confirmation. However, if the webhook is much faster, or retrieving the intent in this method takes a while, it does not. The reason for this is that the webhook handler might have already completed the confirmation/verification process *and* unlocked the order. At this point `WC_Gateway_Stripe::verify_intent_after_checkout` will proceed, because the order status check was performed too early.

This PR moves the order status checks after the retrieval of the PaymentIntent, but also reloads the order before checking the status, to ensure that it has not been completed already.

#### Testing instructions

0. Enable all webhooks.
1. Checkout `master`.
2. Put a timer (`sleep( 10 );`) right after `$intent = $this->get_intent_from_order( $order );` in `verify_intent_after_checkout`. This will simulate a slow PaymentIntent retrival.
3. Create an order. You will see double status changes, and duplicate emails.
4. Checkout this branch.
5. Put the same timer after `$intent = $this->get_intent_from_order( $order );`.
6. A single set of emails should've gone out, and a single order note should be present.

### CODE REVIEW

**Comment by RadoslavGeorgiev** [comment]
A customer reported in 2091550-zen that even though this is partially fixing the issue, there are still duplicates. I'll do some further experiments...

**Comment by RadoslavGeorgiev** [comment]
So, I did have a couple of findings:

## Double notes after capturing a payment later

In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/890/commits/1784ab5b80ec0c98de26839d98b146617ce06083 I added a couple of `$order->save()`s. Double notes were appearing because the order meta was being updated, but not actually saved in the database. Now that they are in place, both instances are aware of each-other.

## Most duplicates were coming from non-3DS payments

In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/890/commits/ed09d5445bb074de56cae9f291fcfaa65013d68d I shuffled things around a bit.

What was happening: In `process_payment`, while trying to confirm the intent, Stripe was sending webhooks synchronously. This means that before `process_payment` can mark the order as paid, the webhook was already doing that, and then `process_payment` did it again.

In order to have `lock_order_payment` and `unlock_order_payment` only appear within a single method (to make the code readable), I had to extract the confirmation out of `create_and_confirm_intent` and `update_existing_intent` as a separate method. This way the order gets locked immediately before the confirmation, and unlocked only once `process_payment` is about to finish.

**Comment by dechov** [comment]
@RadoslavGeorgiev I've read over the changes and they look good – if (as I suppose) we're not releasing today, I'll take a little bit of time to reproduce the issue – let me know if you have testing steps you were working with.

**Comment by RadoslavGeorgiev** [comment]
Sorry, I was so surprised to see how easy they are to reproduce, that I forgot to include instructions. 

For both of findings mentioned above, you need to have web hooks enabled and use a non-3DS card (ex. 4242).

For the issues with delayed capture: Disable the "Charge captures immediately" setting and make a purchase. Before the latest commits/with master, you'd see duplicate notes. 

For immediate capture and non-3DS cards, simply make a purchase with master. You will immediately see the doubled notes and emails. 

This PR should fix both of those issues.

**Comment by RadoslavGeorgiev** [comment]
I see no further issues in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/889 and the support ticket(s) I have access to report that the issue is not appearing anymore. I'll go ahead and merge this in preparation for 4.2.1

**Pull request merged**
