### PR TITLE
Payment method customization

### PR DESCRIPTION
**Pull request by Mayisha**
This PR makes some further implementation of the same settings page on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2750

## Changes proposed in this Pull Request:
- Introduces separate update endpoint for payment method settings. 
- Added necessary actions, selectors and hooks for updating individual payment method settings.
- The changes are saved to the backend when `Save changes` button is clicked now.
- Allows customizing the `card` method also as per design.
- Added the `Expiration` field for the methods that have `expiration` option in settings (Boleto is the only one with this option)

customization section

## Testing instructions
- Go to the Stripe settings page.
- From the `Settings` tab disable UPE. The customization button for each method is available only when UPE is disabled.
- Go to the `Payment Methods` tab. Click the customize button beside any payment method.
- Add a name and description. Click `Save changes`. In the network tab there should be a successful POST request to `<your_site>/wp-json/wc/v3/wc_stripe/settings/payment_method` and the changes should be saved.

### CODE REVIEW

**Review by mattallan — COMMENTED** [review]
Hey @Mayisha 👋 I've have rin through your testing instructions and can confirm the settings page is working according to your steps:

- [x] On the settings page, edit the name and description. Click Save changes.
- [x] In the network tab confirm there's a successful POST request to settings/payment_method and the changes should be saved.

I'm not sure if this is out of the scope of this PR but I noticed a couple of issues I wanted to highlight from my testing:

1. After customizing the name of an individual payment method and then pressing save changes. If I scroll down and press the other save changes at bottom of the page, after refreshing the page the payment method changes I made have been overridden and reverted back to the original name

Here's a screencast:

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/50329363-031e-4423-9130-dbe613adf625


2. After customizing a payment method and pressing "Save changes", if I try to reload the page, I get the browser pop-up saying I have unsaved changes on the page and asking whether I want to reload the page:

image

Because the data has been saved, if I reload the page it's fine.

Apologies if these issue are already planned to be fixed in another PR :)

**Comment by Mayisha** [comment]
Thanks @mattallan for the feedback. I can reproduce both of the issues.

> After customizing the name of an individual payment method and then pressing save changes. If I scroll down and press the other save changes at bottom of the page, after refreshing the page the payment method changes I made have been overridden and reverted back to the original name

This is happening only for the `card` method. In non-UPE mode `card` actually refers to the main Stripe gateway. In the `Settings` tab below enable the Stripe checkbox, there are title and description fields for Stripe which override the same fields in DB as `card`. In the [design](https://www.figma.com/file/xVAk98kbRKUByVTrhPc98g/Stripe-Extension?node-id=625%3A48654&mode=dev), I see that the title and description below the checkbox are not there anymore. So to fix this issue I have removed them from the Settings tab as per design https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2792/commits/710879a9c4b18c74a19bc9a8be22937e3a6c687c


> After customizing a payment method and pressing "Save changes", if I try to reload the page, I get the browser pop-up saying I have unsaved changes on the page and asking whether I want to reload the page.

I noticed that this issue happens for both the customization (this PR) and the change order ([PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2756)) features. Handling this needs a little refactoring, so I plan to fix them together in another PR.

**Comment by mattallan** [comment]
Thanks @Mayisha ! I'm still seeing the same issue on the latest changes (see screencast)

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/27529c21-d324-42a1-9dc7-91116b48cc38

To reproduce:
1. Open the Stripe settings > payment methods tab
2. Click on "Customize" next to the Credit card / debit card payment method
3. Update the title to "Test123" and click "save changes" on the customize tab
4. Scroll down to the bottom of the page and click Save changes
5. Reload the page and notice the new title for Credit card / debit card hasn't been saved.


---

Regarding the "Are you sure you want to reload the page" pop-up:

> Handling this needs a little refactoring, so I plan to fix them together in another PR.

That sounds good to me :+1: THis is already quite a large PR and is being merged into a feature branch so if you'd like to get this merged in and work on the two current issues separate I would support that decision 😄 

There's a lot of conflicting files currently so I can understand wanting to get this merged ASAP

**Comment by Mayisha** [comment]
Thanks @mattallan. I found that I was still sending the Stripe title and description with the POST request which was causing the issue. Fixed it in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2792/commits/6eaf16fe1291bcbf4826eca6b90aa17871042858.

**Review by mattallan — APPROVED** [review]
Amazing work on these set of changes @Mayisha !
I've just tested the latest changes and confirmed the problem I was seeing has been fixed. I also ran through and performed smoke tests for customising/saving various payment methods on stores with US and EU locations/currencies.

I tried to test the Boleto payment method by connecting a Brazilian Stripe account and changed my store location and currency to Brazil but I get a blank list of payment methods:

image

I'm getting the same issue on `develop` branch so I'm guessing there's something wrong with my local dev site that's causing this and it's unrelated to this PR so I'm happy to approve this one.

💯 🚀

**Pull request merged**
