### PR TITLE
Idempotency

### LINKED ISSUE #522: Doesn't handle billing_email changes for pending/failed/recurring charges
If customer changes their billing_email for an order after it was captured under their old billing_email but before the charge has to be rerun (is set in WC to pending payment) payment capture fails. 

This worked fine with v4.0.3, but fails in versions thereafter. This is causing now issues with WC Subscriptions we use.

I believe the billing_email should be meta data but not be tied in anyway to a charge and prevent a rerun of the same order payment at a later time. A CC is not tied to a specific email address - makes no sense. 

Changing billing_name or billing_address, as reported in another issue thread, is a different story as it is tied to a specific CC #. Would be great if these data change for a existing stored CC then in the WC checkout page it selects 'Use a new payment method' and forces the user to enter a new CC #.

### PR DESCRIPTION
**Pull request by roykho**
Fixes #522

#### Changes proposed in this Pull Request:
* Fix - Potential issue when a charge parameter changes due to initial failed request causing retries to fail.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
@roykho if I understand the logic correctly, this would only change the idempotency key if we've gotten a retryable error, correct?

This means it wouldn't handle the following cases:

1) charging the order on a stored card failed -> customers tries again with the same stored card -> we'd get the same decline response due to same idempotency key
2) setting a `processing` order back to `pending_payment` without changing anything else -> sending the customer the pay link -> they pay with the same stored card -> no new charge would be created but the response from the first charge would be returned

IMO, 1) is fine, since we'd want the customer to choose a different card or payment method in that case (although I think yesterday we said we'd want to allow a new charge to happen for up to 5 times, IIRC).
Regarding 2) this might be unexpected, no?

**Comment by roykho** [comment]
@thorsten-stripe 

> if I understand the logic correctly, this would only change the idempotency key if we've gotten a retryable error, correct?

Yes that is correct.

> charging the order on a stored card failed -> customers tries again with the same stored card -> we'd get the same decline response due to same idempotency key

Initially right, then it goes to modify the idempotency with the retry count per our conversation yesterday and you can see that in my screenshot.

> I think yesterday we said we'd want to allow a new charge to happen for up to 5 times, IIRC)

Yes and it does as long as the process fails, it will retry that again up to as many times as we have set the retries for which is 5.

In my test, I checked out with 378282246310005 and saved that card for future use. Then I changed the order status to pending again ( to simulate a failed case ). I then changed billing email parameter. I proceed to pay with the same saved card again. I get the below results.

**Comment by thorsten-stripe** [comment]
@roykho 
> In my test, I checked out with 378282246310005 and saved that card for future use. Then I changed the order status to pending again ( to simulate a failed case ). I then changed billing email parameter. I proceed to pay with the same saved card again. I get the below results.
Yes, I tested this behaviour and got the same outcome. However, if you only change the order status and nothing else; the next charge request will simply return the response of the first charge request and we won't actually retry, because the request wont error:
image

>> charging the order on a stored card failed -> customers tries again with the same stored card -> we'd get the same decline response due to same idempotency key

> Initially right, then it goes to modify the idempotency with the retry count per our conversation yesterday and you can see that in my screenshot.

I don't think this is the case, because charge declined errors are not treated as retryable, right? We unfortunately can't test this because the decline test card will error when you try to attach it to the customer. 

However, from my side, these are fine, and I don't expect them to happen in normal usage.

LGTM

**Comment by roykho** [comment]
@thorsten-stripe 

> I don't think this is the case, because charge declined errors are not treated as retryable, right?

Yes that's correct so this change is really just to prevent parameter change with the same order/source from failing. Do you foresee any regressions by doing this?

**Comment by roykho** [comment]
@thorsten-stripe Also do you reckon the webhook handler would probably also need this change because it is possible that webhook gets triggered before anything else? It can certainly be triggered before redirect handler.

**Comment by thorsten-stripe** [comment]
@roykho 
> Yes that's correct so this change is really just to prevent parameter change with the same order/source from failing. Do you foresee any regressions by doing this?
No, I think that's fine.

> Also do you reckon the webhook handler would probably also need this change because it is possible that webhook gets triggered before anything else? It can certainly be triggered before redirect handler.
> This only concerns reusable sources, which currently are all within the `none` flow (cards & SEPA DD), meaning the webhook handler doesn't trigger for them. Later down the road there might be reusable sources with a different flow (e.g. Alipay reusable with an initial redirect). For these the webhook handler could in fact trigger first.

**Comment by wscheinhart** [comment]
I'm not sure why you are OK with not trying/allowing to handle the case when the client is trying to use the same saved CC for the order after being set to pending payment again. 

It works for 'Not Saved' CC - I can use the same CC in this case and the payment is processed. Only when using a saved card it fails currently. 

It also works when not changing the billing email...which has me still baffled why the billing email changes the outcome. I can use a saved CC and set the order to pending payment again and run the same saved CC OK, but not when the billing email changed for the order in database between the two payment attempts.

**Pull request merged**
