### PR TITLE
Fix php_uname critical error. Fixes #1566

### LINKED ISSUE #1566: php_uname() throwing unnecessary warnings
**Describe the bug**
If the server has disabled the function _php_uname()_ the following warning is thrown whenever the plugin is called, eg during checkout.

`PHP Warning: php_uname() has been disabled for security reasons in /home/wp/disk/wordpress/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-api.php on line 69` 

**To Reproduce**
Disable php_uname() and use the plugin.

**Expected behavior**
`'uname' =>  (!function_exsists('php_uname')) ? false:php_uname(),`
Disabling php_uname() for security reasons is absolutely fine. So the plugin should check if the function is available.

**Environment (please complete the following information):**
 - WordPress Version 5.7.2
 - WooCommerce Version 5.3.0
 - Stripe Plugin Version 5.1.0

### PR DESCRIPTION
**Pull request by kaushikasomaiya**
#1566

This now throws a critical error on PHP 8+ when php_uname is disabled by host.

I've added a function check:

> function_exists( 'php_uname' ) ? php_uname() : PHP_OS

### CODE REVIEW

**Review by reykjalin — APPROVED** [review]
Looks good to me 🚀

**Comment by NoamRabbani** [comment]
Thanks for the quick fix. How do I get this code into my woocommerce-gateway-plugin? Do I need to wait for a new release or  is it already available?

**Comment by kaushikasomaiya** [comment]
@NoamRabbani This will be merged and released soon. I'd suggest waiting for an official update. 

Alternatively, you can do the file change described here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2518/files on your site.

**Comment by NoamRabbani** [comment]
I updated the plugin and re-activated it on my website. It no longers crashes my Wordpress backend. Thx

**Pull request merged**
