### PR TITLE
Update packages for composer v2 compatibilty

### PR DESCRIPTION
**Pull request by reykjalin**
# Changes proposed in this Pull Request

Update `composer.json` and `composer.lock` so that they're compatible with the latest version of Composer.

# Testing instructions

1. Run `composer self-update` to get the latest version of Composer.
1. Run `composer install`.

And make sure no errors occur.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by v18** [comment]
Thanks @reykjalin - does this change need to go in in the upcoming release or can we release it next year?

**Comment by reykjalin** [comment]
We can release it whenever, but working with the latest version of composer will not be possible until this is merged. That might get in the way of some package updates since not all packages are compatible with Composer v2, but I don't see any harm in letting this wait until January.

**Comment by reykjalin** [comment]
I based all the other PRs I made today on this PR, so these changes are reflected in those PRs as well, sorry about that!

This seems to be a pretty mundane change though, and I think we should just merge, and this will disappear from the other diffs.

I think this is especially safe to merge because we're just changing the dev dependencies, nothing has changed that's used in production.

**Review by allendav — APPROVED** [review]
Blew away vendor folder, installed new composer, ran prebuild and ran build for this branch.
Builds fine, resulting plugin tests fine. Happy to be on composer 2.0.8 now. Thank you!

**Pull request merged**
