### PR TITLE
Fix 3DS sometimes causes second payment retry closes #683 #684

### LINKED ISSUE #683: 3DS redirect causes a second retry payment
In this scenario we have 3DS enabled and we are making use of webhooks. The following filter is also being used to require optional 3DS payments (but this doesn't change the behaviour):

```
add_filter( 'wc_stripe_require_3ds', '__return_true' );
```

The scenario which I'm seeing with a live transaction is the following (copied from the log with some data removed):

```
01. 19:14:00 Info: Begin creating 3DS source...
02. 19:14:00 sources request: ...
03. 19:14:02 Info: Redirecting to 3DS...
04. 19:14:26 Info: (Redirect) Begin processing payment for order 8038 for the amount of 10.00
05. 19:14:26 sources/src_ABCHlFLexAc2QLzfoFHwZS3d
06. 19:14:27 Info: (Webhook) Begin processing payment for order 8038 for the amount of 10.00
07. 19:14:27 charges request: ... Idempotent key 8038-src_ABCHlFLexAc2QLzfoFHwZS3d
08. 19:14:27 charges request: ... Idempotent key 8038-src_ABCHlFLexAc2QLzfoFHwZS3d
09. 19:14:29 Info: (Redirect) Begin processing payment for order 8038 for the amount of 10.00
10. 19:14:29 sources/src_ABCHlFLexAc2QLzfoFHwZS3d
11. 19:14:29 charges request: ... Idempotent key 8038-2-src_ABCHlFLexAc2QLzfoFHwZS3d
12. 19:14:31 Processing response: ... ch_ABCHlgLexAc2QLzfHEOtt2Gj
13. 19:14:33 Error: (
    [error] => (
            [charge] => ch_ABCHliLexAc2QLzffl0pf6yi
            [code] => card_declined
            [decline_code] => do_not_honor
            [doc_url] => https://stripe.com/docs/error-codes/card-declined
            [message] => Your card was declined.
            [type] => card_error
        )
)
```

In step 7 and 8 we can see two charge requests with the same idempotent key. The first one is accepted by Stripe and it starts processing the request. For the second one Stripe returns the following response with a status of 409:

```
{
  "error": {
    "message": "There is currently another in-progress request using this Idempotent Key (that probably means you submitted twice, and the other request is still going through): 8038-src_1CYHlFLexAc2QLzfoFHwZS3d. Please try again later.",
    "type": "invalid_request_error"
  }
}
```

Since the error type that is returned is very generic it sees this as a retryable error. So we can see that 2 seconds later there is another charge request sent (step 11). Because it's a retry it uses a different idempotent key. So Stripe sees it as a different charge and sends it through. However it looks like it's denied a little further up (possibly the bank considers it as a duplicate charge), and a card_error is returned.

This has the result that in the order notes. We see both the successful charge but also the card_error which causes the order status to temporarily change to failed.

This scenario mainly depends on how long the successful charge takes to process. In this scenario it took longer then all the other requests so the final order status is marked as processing because of the successful payment. 

On my test site I'm able to replicate a similar scenario. I can see the retry request being sent, but because the successful charge is processed a lot quicker any of the retry requests are cut off a lot earlier.

Sending the retry request can be ok. But it shouldn't be sending it with a new idempotent key since this causes it to try to do a duplicate charge. @roykho suggested to use regexp to check the message content, since the error type is too vague.

Affected ticket: 1205731-zen

### PR DESCRIPTION
**Pull request by roykho**
Fixes #683 #684

#### Changes proposed in this Pull Request:
* Fix - 3DS payment sometimes will create additional transaction in Stripe.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
@mikkamp could you please test this PR out on customer's site and see if it works for them?

**Comment by mikkamp** [comment]
@roykho I sent the patched version for testing. On my test site it works, but I noticed that the webhook handler ignores object->type = three_d_secure.

Because this is ignored, there is no longer a race condition between the redirect handler and the webhook handler. This seems like a good thing as that will prevent even getting the duplicate idempotent keys. But I don't know enough about when the webhooks should fire. Does removing this race condition between the two cause side effects anywhere else? Is the webhook ever needed to process a 3DS transaction?

**Comment by roykho** [comment]
> but I noticed that the webhook handler ignores object->type = three_d_secure

@mikkamp come to think of it, I knew there was a reason why I didn't add that in the first place. I believe 3DS also needs webhooks in certain cases. For example if the customer closes their browser right after they have been redirected to their bank and paid before returning back to the store site.

**Comment by roykho** [comment]
Update - after having re-read the docs, I think we're still ok with this though. Because chargeable state is determined at the time of creating the source and that part is synchronous and does not require webhook which the plugin has done until now. So 3DS cards should never really have a "succeeded" webhook trigger in the first place. I will test this out some more. I will try to bail out right after the redirect before coming back to the site and see what webhooks are fired.

**Comment by mikkamp** [comment]
That was for the fix of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/684
Is there someone from Stripe that can give a bit more info about the difference between not_required and not_supported and which steps it goes through in each case?

**Comment by roykho** [comment]
So in the docs, it states (summarizing) "not_supported" means 3DS is not supported and thus will be processed like a regular credit card. "not_required" means it is a 3DS card and there are two attributes "optional" and "recommended". So if they don't use the "filter to force 3DS" for the optional, it means it will process like a non 3DS credit card. And if they use the "filter to force 3DS", optional will go through the normal 3DS flow. But when the card is 3DS "recommended", it will put them through the 3DS flow.

Does that answer your question? Or do you still feel a Stripe rep is needed to clarify?

**Comment by mikkamp** [comment]
If the decision is to ignore the webhooks from 3DS, then I think we are all fine as it would no longer end up in that same scenario. So everything here looks good then.

Still would need to hear back about the testing from the customer site.

**Pull request merged**
