### PR TITLE
Re-enable Stripe Link for shortcode checkout

### LINKED ISSUE #3379: Stripe Link autofill not working for shortcode checkouts
### **Describe the bug**
Stripe Link autofill does not work for shortcode checkout.

**To Reproduce**

1. Ensure that the Legacy checkout experience is disabled.
   - Go to the Stripe settings tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings` to see the setting.
2. Ensure Stripe Link is enabled.
   - Go to the Stripe Payment Methods tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods` to see the setting.
3. Create a shortcode checkout page, i.e. `[woocommerce_checkout]`
4. Set up your test email with Stripe Link autofill **using the blocks checkout**.
   - As a shopper, add a product to the cart and proceed to blocks checkout.
   - Fill in the billing/shipping details, and credit card information.
   - After typing in your credit card information, you should see an option appear for saving your information with Link, i.e. "Save your info for secure 1-click checkout with Link". See screenshot below. Enter a phone number. (Any phone number will do in Stripe test mode.)
   - Place the order.
5. In the same browser session, add a product to the cart and **go to shortcode checkout**.
6. Notice that the email address field is not empty, but the Link button is not displayed.
   - Compare this with blocks checkout, where the Link button is displayed if the email address field is not empty. This is the expected behavior. See screenshot below.
7. In an incognito browser, add a product to the cart and proceed to _blocks_ checkout.
8. Type in your Link-registered email address, and notice that the Link autofill modal pops up.
9. Repeat this process in a new incognito session for _shortcode_ checkout, and notice that typing in a Link-connected email address does not trigger the autofill modal.

**Expected behavior**
When Stripe Link is enabled, Link autofill should work in blocks checkout and shortcode checkout:
1. The Link button should appear when visiting the checkout page and the email address field is pre-filled. See screenshot below.
2. The Link autofill modal should pop up when I type in a Link-registered email address.

**Screenshots**

Screenshot 1: comparing shortcode checkout vs blocks checkout when the email address field is not empty.
Screenshot 2024-08-21 at 9 15 51 PM

Screenshot 2: Setting up your email with Stripe Link.
Screenshot 2024-08-23 at 11 48 13 AM

**Environment (please complete the following information):**
Stripe plugin >= 8.0.0

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3379 

## Changes proposed in this Pull Request:

In moving to deferred intents (>= 8.0.0), we unintentionally dropped Stripe Link autofill functionality for shortcode checkouts.

This PR adds back support for Stripe Link autofill in shortcode checkouts.

## Testing instructions
1. Set up Stripe Link and shortcode checkout.
   - Ensure that the Legacy checkout experience is disabled in the Stripe settings tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`.
   - Ensure Stripe Link is enabled in the Stripe Payment Methods tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`.
   - Create a shortcode checkout page, i.e. `[woocommerce_checkout]`
2. Test "new email" scenario:
   - Get a test email from https://10minutemail.com/ or a similar service. This can be skipped if you're fairly certain that your test email has not been registered with Stripe Link yet.
   - Add a product to your cart and go to the shortcode checkout page.
   - Enter your name, billing/shipping details, and test credit card info.
   - As you type the test credit card info, a box asking you to register with Stripe Link should appear. (See Screenshot 1.)
   - Enter any phone number, e.g. `(800) 555-0175`.
3. Test "returning email" scenario:
   - Add a product to your cart and go to the shortcode checkout page.
   - Depending on whether the email address field is blank or not when you load the shortcode checkout page, do the following: 
       - Email address field is not blank: you should see the Stripe Link logo beside the email address field. Clicking the logo should launch the autofill modal. (See Screenshots 2 and 3.)
       - Email address field is blank: type in the same email you used in the "new email" scenario. The Stripe Link autofill modal should appear, asking you for the one-time code. Note: you can force this path by testing on an incognito browser. (See Screenshot 3.)
   - Enter "000000" as the one-time code. It should bring up the customer information attached to this email address, the same one you entered in the "new email" scenario.
   - Click "Autofill checkout" and verify that the name, billing and shipping address fields, and credit card information have been autofilled correctly.
4. Test for unintended regressions:
   - Verify that these changes did not affect blocks checkout by running through the "new email" and "returning email" scenarios for the blocks checkout.
   - Verify that legacy checkout is unaffected:
       - Enable the Legacy checkout experience in the Stripe settings tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`.
       - Add a product to the cart and go through shortcode checkout.
       - Add a product to the cart and go through blocks checkout.
   - Verify that this does not affect checkouts when Stripe Link is not enabled.
       - Disable Stripe Link in the Stripe Payment Methods tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`.
       - Add a product to the cart and go through shortcode checkout.
       - Verify that no Stripe Link elements (e.g. autofill modal, logo beside email address, registration box) appear during the checkout process.
       - Go through the same for blocks checkout.
       
Known limitations/expected behavior of Stripe Link autofill modal:
- You can only launch the autofill modal once per page load. You will need to refresh the page to reset the process.
- If the email address is not registered, clicking the logo will not give any feedback.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply) -- DevTools only

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

**Screenshots**

Screenshot 1: registering with Stripe Link
register-with-stripe-link

Screenshot 2: email address field with the Link logo
stripe-link-button

Screenshot 3: the Link autofill modal
stripe-autofill-modal

### CODE REVIEW

**Comment by wjrosa** [comment]
@annemirasol Your testing instructions mention screenshots. I think you forgot to include them.

**Comment by annemirasol** [comment]
> @annemirasol Your testing instructions mention screenshots. I think you forgot to include them.

Oof, thanks! Added.

**Review by wjrosa — APPROVED** [review]
Code looks good and it works as expected! Good job, Anne! 🚀 

Screenshot 2024-08-26 at 15 49 53

**Comment by Mayisha** [comment]
Good work @annemirasol 🎉 

The PR looks good and it's good to go. 

As I was testing the PR, I came across one issue that is unrelated to this PR. I am adding it for documenting. The steps to reproduce the issue are-

- Add a product to your cart and go to the checkout page.
- Use an email that has a Link account, click the link button to open the modal.
- Verify OTP and click "Autofill checkout". 
- Now click the "Place order" button and complete the checkout.
- Now add another product to the cart and go to the checkout page.
- Notice that in the payment method section, the saved card from Link is already there.

Screenshot 2024-08-27 at 11 31 54 PM

- Now change the email address to something new and click the place order button.
- The checkout fails with the error `Your card number is incomplete`

Screenshot 2024-08-27 at 10 31 28 PM

**Comment by annemirasol** [comment]
> * The checkout fails with the error `Your card number is incomplete`

Good catch! This is a curious bug, so I spent some time looking at it, checking whether the fix is small enough to include with this PR. Spoiler alert: it's not :/

Some of my findings, which I will also write in more detail in the ticket I plan to create.
1. On keyup and logo button click, we call `linkAutofill.launch()`, passing the email as param. 
    - If the email is registered with Link, the OTP modal pops up. If not, there is no feedback to the user, and there is no return value to help us programmatically detect what happened. 
    - There are two events we can hook into: `autofill` and `authenticated`, covering only positive scenarios. 
3. When `linkAutofill.launch()` does not lead to a successful authentication, i.e. email not registered, or the user closed the modal without authenticating, the user can get caught in an inconsistent state. This is the scenario you discovered: the payment element displays a saved payment method, but it does not actually have that payment method.
4. One way to clear the payment element display requires the user to manually click `Change` > `Log out of Link` (see screenshot). Programmatically, `linkAutofill.logout()` will do this. However, it errors out when the user is "not logged in". It only considers the user as "logged in" after a successful `linkAutofill.launch()` -- which is the opposite of our scenario, and does not help us.
5. A possible mitigation here is to remove the keyup listener when the email address field is not blank, and there are Link payment methods loaded. Removing the keyup listener will let us avoid triggering `linkAutofill.launch()` unnecessarily.
    - If a user wants to change the Link account loaded, they need to type in the email and click the Link logo.
    - This is only a mitigation as failure to authenticate when the logo is clicked will lead to the same buggy behavior.
    - From the UX side, I don't know if we want users to be able to change their email address but still use payment methods saved in Link via a different email address.

**Comment by annemirasol** [comment]
As [the discovered issue](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3380#issuecomment-2313147816) has existed prior to this PR, and is not a trivial fix, I will go ahead and merge this one.

**Comment by wjrosa** [comment]
Hey @annemirasol ! Can you create an issue for this bug, please? If it does not exist already.

**Comment by annemirasol** [comment]
> Hey @annemirasol ! Can you create an issue for this bug, please? If it does not exist already.

Working on it 🫡

**Comment by annemirasol** [comment]
> > Hey @annemirasol ! Can you create an issue for this bug, please? If it does not exist already.
> 
> Working on it 🫡

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3389

**Pull request merged**
