### PR TITLE
Add account summary API endpoint

### LINKED ISSUE #2121: Add API endpoint for Stripe account details
**Description**

For in-person payments, the mobile application will need to call an endpoint to fetch details of the Stripe account attached to the store. This is used to determine if the account is fully set up and eligible for in-person payments.

Sample response:

```
{
  "data": {
    "has_pending_requirements": false,
    "has_overdue_requirements": false,
    "current_deadline": null,
    "status": "complete",
    "statement_descriptor": "DO.WPMT.CO",
    "store_currencies": {
      "default": "usd",
      "supported": ["usd"]
    },
    "country": "US"
  }
}
```

**Additional context**

pdfdoF-er-p2

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #2121

## Changes proposed in this Pull Request:

For Stripe Terminal support, the mobile apps need to be able to get some details of the Stripe account. The Stripe extension already has an API endpoint (`wc_stripe/account`) to get full account details, but the mobile apps need the data returned in the same format that WCPay uses in its own account endpoint (WCPay does some additional processing to determine whether account requirements are met).

This PR adds another endpoint (`wc_stripe/account/summary`) to return account details in the same format as WCPay.

Additional Context: pdfdoF-er-p2

## Testing instructions

For making API requests, I found it helpful to install the [Basic Auth](https://github.com/WP-API/Basic-Auth) plugin to my test site so that I could make requests of the form `curl --user username:password 'http://YOUR_SITE/wp-json/wc/v3/wc_stripe/account/summary'` to test the endpoint.

1. Run `curl --user username:password 'http://YOUR_SITE/wp-json/wc/v3/wc_stripe/account/summary'`
2. Verify that the response you get matches the format of the response under the `data` key in the "Load Account" section of pdfdoF-er-p2.
3. To test making a change to the account details, go to your Stripe settings (https://dashboard.stripe.com/settings/account) and change your statement descriptor.
4. Delete the `_transient_wcstripe_account_data_test` transient from the `wp_options` table to force the API to load the data from Stripe on the next request.
5. Run `curl --user username:password 'http://YOUR_SITE/wp-json/wc/v3/wc_stripe/account/summary'` again, verify that you see your new statement descriptor in the response.

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Review by malithsen — COMMENTED** [review]
Nice work here @brianyu28. Testing this locally with test stripe accounts the new endpoint returns expected results. I have one minor question, which may not be strictly relevant to the changes made here. 

`WC_REST_Stripe_Account_Controller` class the new endpoint resides in, only gets registered when ` WC_Stripe_Feature_Flags::is_upe_preview_enabled() ` is true https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/woocommerce-gateway-stripe.php#L597

Is UPE really required to return stripe account data?

**Comment by brianyu28** [comment]
Good catch, thanks @malithsen! I've moved the account controller outside of the feature flag check so that it's available even without UPE. Looping in @cesarcosta99 as well to take a look too and confirm that it's okay to move it, since I see you're the Fractal PR reviewer for this week.

**Review by malithsen — APPROVED** [review]

**Review by cesarcosta99 — APPROVED** [review]
LGTM 🚢 

I noticed that the endpoint specifications present in the P2 (pdfdoF-er-p2) contain two extra properties: `is_live` and `test_mode`. I wonder if this is something we should tackle over here, however it can be addressed later on, if necessary.

>Is UPE really required to return stripe account data?

Not really, in fact, that feature flag is intended to be removed soon.

**Comment by brianyu28** [comment]
Thanks! I'll merge this now and add the `is_live` and `test_mode` in an additional PR. In the Stripe extension, is it accurate to say that `is_live` should always be the opposite of `test_mode`?

**Comment by cesarcosta99** [comment]
>is it accurate to say that is_live should always be the opposite of test_mode?

I'd suppose so, we have to confirm their definitions and purposes first. Based on their name, I'd guess they have different types.

**Comment by allendav** [comment]
Thank you @brianyu28 - this is awesome. Regarding `is_live` and `test_mode`:

`is_live` indicates that the underlying Stripe account is not just a developer account but an actual account connected to a bank, etc. If the account was created with the stripe dashboard in test mode, you'll get an is_live:false account.

`test_mode` indicates that this payment gateway extension should use test keys instead of live keys

So, they aren't opposites - e.g. you can have is_live:true with test_mode:true or test_mode:false

We ideally want is_live and test_mode in the endpoint response - what PR / issue will bring that?

fyi @malinajirka @ctarda 

Edit: Related iOS pull: https://github.com/woocommerce/woocommerce-ios/pull/5799

**Comment by brianyu28** [comment]
Thanks for clarifying, @allendav! I've just created https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2262 to track the issue, and will follow up here with a PR when ready.

**Pull request merged**
