### PR TITLE
Avoid re-mounting card elements if already in DOM

### LINKED ISSUE #507: Card details get deleted when shipping/billing details are changed
#### What I expected

Card details shouldn't get deleted, this is not expected behaviour. A customer might realise their card is registered to a different address after entering it and want to change the billing address, for example.

#### What happened instead

If the tickbox to enable a different shipping address is toggled, the card details are removed. Same if post code and other fields are changed

#### Steps to reproduce the issue

1. Fill in billing details
2. Fill in card details
3. Tick ship to a different address
4. Note that the card details get annihilated

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by dechov**
Fixes #507 in combination with https://github.com/woocommerce/woocommerce/pull/24227

#### Changes proposed in this Pull Request:

To avoid unnecessarily clearing any payment information already entered: when checkout is updated, check if the elements are still mounted in the DOM before proceeding to re-mount.

Note that if the total price changes (due to shipping and/or tax rate difference for the changed address), the fragment will still be replaced and so the elements will still re-mount – this is because the amount is included in the markup [[commit](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/ba70a8291388bdaf69a6db4d68e7a9fb1290d55c)].

Tested using the instructions in https://github.com/woocommerce/woocommerce/pull/24227

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by v18** [comment]
I like this change a lot, along with woocommerce/woocommerce#24227, kudos @dechov. Neat.

The testing instructions worked for me.

### Note on `payment_fields()` changes

Note that `elements` will not be unmounted even if the order total changes since that's no longer being outputted since https://github.com/woocommerce/woocommerce-gateway-stripe/commit/54fb68ce56b9fa75b0293d3f5d9fa321518d966e#diff-2f62df4143b223ac0f7805c02376412e

This was done in this PR:

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1024

It's not clear from the PR description why `data-amount` was removed from the fragment. @DanReyLop do you recall? I wonder if it's ok to rely on that change going forward, or if we'll want to add it again later. (Getting an answer here is not a blocker for merge.)

### What's solved for me with this PR

This PR covers these issues as outlined in the original report #507:
- If the tickbox to enable a different shipping address is toggled
- if post code and other fields are changed
- entering a coupon code

Not easy to test this case, but likely this is also fixed:
- When working with Cartflows plugin and using order bumps, this also triggers an update and the fragment replaces the entire stripe form which is counter intuitive

### Other notes

Although we need the update to WC (woocommerce/woocommerce#24227) for this "feature" to work, the code in Stripe only relies on checking whether or not the Elements is mounted on the `updated_checkout` event, so it should work regardless of the technical implementation in WC.

Before merging, the build step needs to be rerun since it's been a while and master has been updated.

I want to point out a couple of caveat, which is not a blocker for merging per se:

1. This is slightly brittle solution within this gateway extension. For example if we re-added the `data-amount` to the fragment. Or if we added other parts to the fragment that would change when the checkout changed. I wonder if there's a way to make this less brittle, for example via a unit test or e2e test checking that the fragment does not rely on the cart total.

2. Do we know if there are plans to merge woocommerce/woocommerce#24227 or something along those lines soon?

Feel free to merge at any time after updating the build 🚢

**Comment by DanReyLop** [comment]
> It's not clear from the PR description why data-amount was removed from the fragment. @DanReyLop do you recall?

It was dead code, neither the `data-amount` or the other `data-*` paramters were being used anywhere in the client JS.

**Comment by v18** [comment]
> It was dead code, neither the data-amount or the other data-* paramters were being used anywhere in the client JS.

👌

**Comment by dechov** [comment]
> Do we know if there are plans to merge woocommerce/woocommerce#24227 or something along those lines soon?

I don't know of any plans to review or merge the WC PR, though I hope to have it considered for the next minor release. Thanks for the review here!

**Comment by dechov** [comment]
Following up to note that the core PR is now merged (slated for 3.9).

**Pull request merged**
