### PR TITLE
add payment method Stripe Przelewy24 (P24)

### PR DESCRIPTION
**Pull request by thorsten-stripe**
@roykho I wanted to get a feeling for how easy it is to add a new payment method with the example of adding P24 which is very similar to iDEAL in its flow: https://stripe.com/docs/sources/p24

However, I think I'm missing a couple of things, and I would highly appreciate if you could review and assess what I'm missing. From what I can see I'm missing the following bits:

* no P24 logo in payment font (any idea if that's easy to add?)
* "Refund via Stripe P24" is disabled (couldn't find how to enable it)
* Order in the wc-settings (for some reason it's listed before Stripe in the "Checkout options" breadcrumb menu, no idea why)
* missing mentions in `languages/woocommerce-gateway-stripe.pot` file (do I just add any references to lines that "print" some text?)

Am I missing anything else?

But if this would be more work than just trashing this branch and adding P24 yourself I totally understand, and feel free to do exactly that ;)

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
@thorsten-stripe I believe P24 is in preview? When will it be available for public?

**Comment by thorsten-stripe** [comment]
@roykho we've moved it into open preview, meaning it's available to all European merchants that want to charge their PL customers in PLN or EUR using the P24 payment method.

**Comment by roykho** [comment]
@thorsten-stripe 

> no P24 logo in payment font (any idea if that's easy to add?)
Yeah so the paymentfont set doesn't include P24 logo.

> "Refund via Stripe P24" is disabled (couldn't find how to enable it)
This is because you have copied the older version of iDeal.

> Order in the wc-settings (for some reason it's listed before Stripe in the "Checkout options" breadcrumb menu, no idea why)
This is reordered in the main plugin file https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/woocommerce-gateway-stripe.php#L353

> missing mentions in languages/woocommerce-gateway-stripe.pot file (do I just add any references to lines that "print" some text?)
Don't worry about this as we rebuild this before deployment.

Since you did not use the latest iDeal file, I am worried some of your other updates may be made on older files too.

**Comment by thorsten-stripe** [comment]
@roykho yes, true, I made a mistake there and used an older version as the basis for `includes/admin/stripe-p24-settings.php` and `includes/payment-methods/class-wc-gateway-stripe-p24.php` . I'll rework.

**Comment by thorsten-stripe** [comment]
okay, now worked off the newest stripe-ideal base and added admin ordering.

Any idea how to approach the logo topic?

**Comment by roykho** [comment]
@thorsten-stripe 
> Any idea how to approach the logo topic?

Not too sure yet.

**Pull request merged**
