### PR TITLE
Add address line 2 for shipping

### PR DESCRIPTION
**Pull request by maxrabin**

### CODE REVIEW

**Comment by roykho** [comment]
Can you please show references/documentation to this parameter?

**Comment by maxrabin** [comment]
[Woocommerce `address_2`](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Abstract_Order.html#17)
[Apple' Pay's `addressLines` is an array](https://developer.apple.com/reference/applepayjs/paymentcontact/1916103-addresslines) ([full `PaymentContact` reference](https://developer.apple.com/reference/applepayjs/paymentcontact))

**Comment by roykho** [comment]
So I am not seeing where it was referenced/documented as an array is where I am skeptical. But have you tested this to be working?

**Comment by maxrabin** [comment]
image
Yes  its tested, see screenshot.

The reference is in https://developer.apple.com/reference/applepayjs/paymentcontact/1916103-addresslines where it declares it as `sequence < DOMString > ` as opposed to just being a `DOMString` like [familyName](https://developer.apple.com/reference/applepayjs/paymentcontact/1916101-familyname)

**Comment by roykho** [comment]
Thanks for the PR!

**Pull request merged**
