### PR TITLE
Fix inconsistent payment processing error messages

### LINKED ISSUE #1187: Inconsistent Error Code Messages
See here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8ed8a390e3a7e782d775d7c29b1c38b8a10c0eb0/includes/class-wc-stripe-helper.php#L209-L226

There is a mixture of "card" and "card's" wording. All of these notices would work with "card", for example:

> The card\'s expiration month is invalid.

Becomes:

> The card expiration month is invalid.

This also avoids the need to escape the `'` in the translation string.

### PR DESCRIPTION
**Pull request by reykjalin**
# Changes proposed in this Pull Request:

Fixes #1187

- Change all occurrences of "card's" to "card" to simplify the messaging.

# Testing instructions

N/A

These strings should never be displayed to a customer because they're handled by Stripe's Card Element or we display the error coming directly from Stripe. The strings are only used to create order notes for the merchant.

You can verify this by trying to checkout with `4000 0000 0000 0127` which is supposed to return `incorrect_cvc`, but instead of the customer seeing the string we provide:

> The card security code is incorrect.

The customer will instead see

> Your card's security code is incorrect.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by v18** [comment]
> These strings should never be displayed because they're handled by Stripe's Card Element or we display the error coming directly from Stripe. The strings are only available in the codebase to fall back on if something extremely weird happens.

> You will instead see
>> Your card's security code is incorrect.

A couple of questions:
1. If the strings aren't being used, should they be removed?
2. Where is the error message that's actually shown coming from ("Your card's security code is incorrect.")?

**Comment by reykjalin** [comment]
> If the strings aren't being used, should they be removed?

I don't think so. From what I can tell, we could feasibly receive these responses from Stripe, and these strings are used to generate Order Notes:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e4c7fcfdd56eebc73c90726be9e6b2da4980b7cf/includes/class-wc-gateway-stripe.php#L818-L844

> Where is the error message that's actually shown coming from ("Your card's security code is incorrect.")?

From Stripe's API:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e4c7fcfdd56eebc73c90726be9e6b2da4980b7cf/assets/js/stripe.js#L667

That said, we do handle _some_ responses there, the issue is that Stripe's JS handles most of these _before we ever send a request_.

For example, if you try to enter the wrong year you'll see this before you try to checkout:

image


## So then when are these strings useful?

When something in Stripe's JS fails and we generate order notes to inform the merchant of what happened. I missed that during my initial work on this, and I've updated the PR description to reflect this.

Even then, most of these are impossible to check, since they're handled by Stripe's JS long before you submit the checkout form. The strings are still important to keep in I think.

**Comment by reykjalin** [comment]
I should add that you don't actually see the string we provide in the order notes for the only card number that can be tested, because it's caught as an SCA error and handled here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e4c7fcfdd56eebc73c90726be9e6b2da4980b7cf/includes/class-wc-gateway-stripe.php#L1158-L1170

But not handled as a payment processing error.

So there's really no way to test any of these strings unless something in Stripe's JS fails 🤷

**Review by dechov — APPROVED** [review]
I don't fully understand the motivation for the change – I think the inconsistency is due to "card number" being a more standard / common phrase than "card's number", which isn't quite the case for "card expiration year", "card zip code", etc. – but approving since I see no harm in the change 😄

**Comment by v18** [comment]
Happy to leave it as is - thank you @reykjalin @dechov for flagging!

**Pull request closed without merging**
