### PR TITLE
Add context to "Discover" when referring to credit card name

### PR DESCRIPTION
**Pull request by d-alleyne**
## Changes proposed in this Pull Request:

The Discover credit card payment method needs to be translated differently from the other instances of the word "Discover".

Related # 533-gh-Automattic/i18n-issues 

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by nerrad** [comment]
I don't really work regularly in this repository so I shouldn't be reviewing it. I assigned @reykjalin who should know who to refer this to for review (or whatever the team's triage process is for this repo).

**Review by reykjalin — APPROVED** [review]
Looks good to me! 💯

**Comment by reykjalin** [comment]
For future reference you can ping Fractal's porter (always up-to-date in the P2 sidebar on +heyfractal) for reviews. This was a tiny change, so pinging anyone is fine 🙂

**Comment by reykjalin** [comment]
@diegocurbelo can we get this into the next release?

**Pull request merged**
