### PR TITLE
Integrate express payments buttonAttributes API from the Checkout Block

### PR DESCRIPTION
**Pull request by alexflorisca**
## Changes proposed in this Pull Request:

This PR uses the `buttonAttributes` API introduced in Woo Core in [Add new buttonAttributes API to style express checkout buttons coherently](https://github.com/woocommerce/woocommerce/pull/47899). This will respect the new `height` and `borderRadius` controls on the express checkout block, overriding extension settings when these are available. It also uses the `darkMode` setting to override the button theme.

This means the Stripe specific settings are still applied if we're not in a checkout block context. But if we are, the button styles will be synced across all express payment buttons that have integrated with this API.

**Note:** At the moment, the borderRadius property is not available on the PRB API. This will be used once the switch is made to ECE.

## Testing instructions

1. Add some items to the cart and visit the cart page (with the cart block)
2. Ensure the express payment method is visible there (Link, GPay or Apple Pay)
3. Click "Proceed to checkout"
4. Ensure the express payment method is visible there too
5. In a new tab, open the checkout page in the editor.
6. Click on the express checkout area and change the button size to "Large"
7. The express payment button height should be `55px`
8. Visit the express payment settings page.
9. A notice should read `Some appearance settings may be overridden by the express payment section of the Cart & Checkout blocks.`
10. Check the link takes you to the Checkout Block

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by alexflorisca** [comment]
Not sure about your release process or which version this will end up in so I've not edited the changelog. Let me know what you prefer here.

**Comment by alexflorisca** [comment]
It's worth noting here that it was decided to postpone the release of the `buttonAttributes` API until WC 9.4 release. The code here should work regardless, as we're checking to see if the type of `buttonAttributes` is `undefined`. However, testing should be done against the `feature/express-payment-improvements` branch in Woo Core. The PR that contains this work is https://github.com/woocommerce/woocommerce/pull/50791. 

One of the reasons we did this is to allow the major payment gateways to integrate with this before we ship it. So this should still be merged and released ahead of Woo Core.

**Comment by alexflorisca** [comment]
Just a note to say that the `darkMode` prop was removed from the API in https://github.com/woocommerce/woocommerce/pull/51109. I just updated this PR accordingly

@diegocurbelo How's the review for this going?

**Review by wjrosa — APPROVED** [review]
Change looks good and it works as expected:

> 2. Ensure the express payment method is visible there (Link, GPay or Apple Pay)

https://github.com/user-attachments/assets/5f15294c-acae-48eb-b68e-53012947e912

> 4. Ensure the express payment method is visible there too

https://github.com/user-attachments/assets/fe44ecc3-c710-4931-811a-d8280b9a40d4

> 7. The express payment button height should be 55px

https://github.com/user-attachments/assets/551a3e3f-db64-44d7-824c-af78e3ad80ad

> 9. A notice should read Some appearance settings may be overridden by the express payment section of the Cart & Checkout blocks.

Screenshot 2024-09-04 at 11 39 41

> 10. Check the link takes you to the Checkout Block

It does 👍

**Pull request merged**
