### PR TITLE
Add the WordPress.com Stripe Connect User Account field to settings

### LINKED ISSUE #312: Support Stripe Connect account when instantiating Stripe
Upcoming work on WooCommerce Services will likely rely on this existing Stripe extension for accounts created on the Connect platform.

We'll need a way to specify the `stripeAccount` option when instantiating the `Stripe` object. See: https://stripe.com/docs/stripe.js#including-stripejs

👋  @mattyza

### PR DESCRIPTION
**Pull request by allendav**
Fixes #312 

#### Changes proposed in this Pull Request:
- Simply adds the field to settings. We cannot use the field in the context of the plugin, but API clients like Calypso will find the field value useful if present.

#### To Test:
- Make sure the setting is NOT displayed at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
- Make sure you see the setting in the response to `/wp-json/wc/v2/payment_gateways/stripe`
- Make sure you can update the setting via the API e.g.

screen shot 2017-08-11 at 10 02 13 am

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
This has no benefit for self hosted users and it could only cause confusion. Can you not just save it in settings without having an UI for it? Also we're no longer working with master branch. 4.0.0 is in development -- best to use that branch although things are changing constantly as its WIP.

**Comment by allendav** [comment]
@roykho @kellychoffman @mattyza @pmaiorana - I am trying to be very deliberate about how this is worded / referred to / named - here's what i have now - please let me know if we want to word / name this differently

wordpress-dot-com-stripe-connect-user-account-id

Ideally, one day, when we have a webpage describing the joys of using our platform, we should add a learn more link to this field.

**Comment by allendav** [comment]
@roykho wrote

> This has no benefit for self hosted users and it could only cause confusion. Can you not just save it in settings without having an UI for it? Also we're no longer working with master branch. 4.0.0 is in development -- best to use that branch although things are changing constantly as its WIP.

OK - let's make it a hidden field for now, and per our convo in slack we'll put this in 3.2.3

**Comment by pmaiorana** [comment]
Hidden field makes sense to me +1

**Comment by allendav** [comment]
Wait - we might not need this after all since we need to store a mapping of connected site and connected user elsewhere anyways - closing without merging - can always reopen later if desired

**Pull request closed without merging**
