### PR TITLE
Hide secret key and webhook secret

### LINKED ISSUE #2508: Stripe secrets should be write only
We should be doing more to keep the Secret Key and Webhook Secret for the "Stripe Account Keys and Webhooks" settings from being accessible, even by other site administrators.  These keys are pretty important, especially the Secret Key as it can give a user access to the make changes on the backing Stripe account where they may not have access otherwise.

Because of this, we should avoid rendering these secrets back to the browser and only allow them to be written to from the settings screen.

Screenshot 2022-12-23 at 10 50 48 AM

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2508 

## Changes proposed in this Pull Request:
The Stripe secret keys should not be visible in the UI as it can give a user access to make changes on the Stripe account. This PR replaces the full keys with masked versions in the frontend.

Additional context here: pc4etw-X0-p2

## Testing instructions
1. Go to **WooCommerce > Settings > Payments > Stripe > Settings** and click `Edit account keys`.
2. Verify that the keys are masked:
    Screenshot 2024-02-15 at 23 52 26
3. Save changes without modifying any values
4. Verify in the database that the keys were saved correctly (no masking):
    `SELECT * FROM wp_options WHERE option_name = 'woocommerce_stripe_settings'`
5. Click `Edit account keys`
6. Change the `publishable key` to an invalid value like `pk_test_INVALID VALUE`
7. Click the `Test connection` link in the bottom left corner
8. Check that the connection error message is displayed:
    Screenshot 2024-02-15 at 23 59 39
9. Change the `publishable key` to a valid value (from your [Stripe dashboard](https://dashboard.stripe.com/test/apikeys))
10. Click the `Test connection` link in the bottom left corner
11. Check that the connection error message is displayed:
     Screenshot 2024-02-16 at 00 01 22
12. Click `Save test keys`
13. Verify in the database that the keys were saved correctly (no masking):
    `SELECT * FROM wp_options WHERE option_name = 'woocommerce_stripe_settings'`

### CODE REVIEW

**Comment by james-allan** [comment]
Hey @Mayisha, I just asked a clarifying question (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2508#issuecomment-1769648241) on the issue because I suspect it was suggesting we go further than using a password type.

**Comment by Mayisha** [comment]
@james-allan I have changed the solution and now instead of using the password field, I am following the suggestion mentioned in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2643.

However, I found two issues with the expected behavior (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2508#issuecomment-1777310409). I am now confused about the best solution here.

**Comment by wjrosa** [comment]
This code looks good to me! But to add to the security discussion, we could:
- Create a new endpoint on the backend that just returns the current state of the keys: set, not set
- When rendering the form with the keys, it will be empty if the above return "not set" or always the same fake masked value if set
- If the form changes and the user clicks the save button, we persist the new data

This way we skip the need of retrieving the current value. We just saves a new value.

**Comment by diegocurbelo** [comment]
> This code looks good to me! But to add to the security discussion, we could:
> 
> * Create a new endpoint on the backend that just returns the current state of the keys: set, not set
> * When rendering the form with the keys, it will be empty if the above return "not set" or always the same fake masked value if set
> * If the form changes and the user clicks the save button, we persist the new data
> 
> This way we skip the need of retrieving the current value. We just saves a new value.

I don't think I understand the benefit of adding another endpoint (and another request to the server) to render the modal, we still need to fetch the masked key values to "preload" the form.

The plugin settings are loaded during the plugin init() in the backend, but only the masked keys are sent to the frontend to populate the modal; the secret key never leaves the server.

**Review by wjrosa — APPROVED** [review]
LGTM!

- Keys are masked
Screenshot 2024-02-21 at 16 46 06

- But are persisted in full
Screenshot 2024-02-21 at 16 50 07

- Connection test fails with an invalid key
Screenshot 2024-02-21 at 16 49 16

- And it works with the valid one
Screenshot 2024-02-21 at 16 49 52

- When fixed, it stores the correct value again
Screenshot 2024-02-21 at 16 52 01

**Review by james-allan — APPROVED** [review]
I've also tested these changes and they work well for me. I tested that the keys are suppressed with *, saving, testing and using the saved keys with purchases etc still work as expected.

**Pull request merged**
