### PR TITLE
🎉 Add view of fees in graphic reports

### PR DESCRIPTION
**Pull request by rvola**
Hi the team !!

I have just created a Class which allows to display in the reports of WooCoommerce, Comissions Stripes. It also recalculates the net sales amounts (sale - vat - delivery - commissions)

I am available to provide answers and support to the team!

### CODE REVIEW

**Comment by roykho** [comment]
Thanks but not needed at this time.

**Comment by rvola** [comment]
Hello @Roykho,

Even if the pull-request is not necessarily added, I am disgusted and do not understand these systematic refusals. I made a request on version 3.X #364  which was rejected, because of version 4.0 which was going out.

And now I am still refused.
It seemed relevant to me to be able to add new features.

Can you give reasons for systematic refusals, because I do not see the internet being on GitHub if you refuse the helpers (I'll add that I'm documenting the code, and I'm ready to explain)

**Comment by roykho** [comment]
@rvola closed PR doesn't mean it may not get reconsidered for addition in the future. It is just not something we're looking to add right at this time. However if in the future something like this is needed, we will gladly reopen the PR.

**Comment by roykho** [comment]
@rvola before you make any PRs, it is best to check in with us first to see if that is something we need/want. So is to not waste your time as well.

**Comment by rvola** [comment]
ok, I understand, the goal of open source is to make the product better by sharing. WooCommerce displays charts to measure sales, there is even a line that displays the "Net" amount corresponding to the product without VAT or delivery.

As an e-commerce manager using Stripe that applies commissions, I find it relevant to be able to quickly view the amounts of these and calculate a fair "Net".

Basically I worked this class on my free time for a client. I wanted to share the community by making a pull-request.

I hope to have my work published later.

**Pull request closed without merging**
