### PR TITLE
[Klarna] Only display it when the presentment currency matches the currency of the customer’s country

### LINKED ISSUE #3118: [Klarna] Only display it when the presentment currency matches the currency of the customer’s country
**Describe the bug**

For transactions between the EEA, UK, and Switzerland, the presentment currency [must match the currency of the customer’s country](https://docs.stripe.com/payments/klarna#:~:text=Swedish%20business%20can%20present%20in%20EUR%20to%20accept%20Klarna%20from%20a%20buyer%20in%20Germany).

Currently, we display this payment method on the checkout page for all these billing countries, but the presentment currency matches the Stripe account's country, not the customer's.

When this happens, the following error is displayed on the checkout page:

```There was an error processing the payment: The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.```

And this Stripe's response body of this request that fails with a 400:

```
{
  "error": {
    "message": "The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_xyz",
    "type": "invalid_request_error"
  }
}
```

**To Reproduce**
1. Connect a Stripe account from the UK
2. Select Pound sterling as the store currency
3. Enable Klarna
4. As a shopper, add a product to the page and proceed to checkout
5. Select France as the billing country
6. Notice Klarna continues to be displayed as an available payment method
7. Place the order using Klarna
8. Notice the error message mentioned about is displayed

**Expected behavior**
Klarna must only be displayed on checkout for cross-border payments when the order currency matches the currency of the customer's country.

For example:
- A Swedish business can present Klarna for a buyer in the EEA when the store currency is EUR
- A business in the EEA can present Klarna for a buyer in the UK when the store currency is GBP

**Additional context**
We'll need to update the checks related to [domestic transactions](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L237-L246) and to customer's billing country.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3118 

For transactions between the EEA, UK, and Switzerland, the presentment currency [must match the currency of the customer’s country](https://docs.stripe.com/payments/klarna#:~:text=Swedish%20business%20can%20present%20in%20EUR%20to%20accept%20Klarna%20from%20a%20buyer%20in%20Germany).

Currently, we display this payment method on the checkout page for all these billing countries, but the presentment currency matches the Stripe account's country, not the customer's.

When this happens, the following error is displayed on the checkout page:

`There was an error processing the payment: The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.`

## Changes proposed in this Pull Request:
- In `get_supported_currencies` function, returning the currency based on the customer billing address for EEA, UK, and Switzerland.

## Testing instructions

**Steps to reproduce**

1. Checkout to `develop` branch.
2. Connect a Stripe account from the UK.
3. Select Pound sterling as the store currency.
4. Enable Klarna.
5. As a shopper, add a product to the page and proceed to checkout.
6. Select France as the billing country.
7. Notice Klarna continues to be displayed as an available payment method.
8. Place the order using Klarna.
9. Notice the error message mentioned about is displayed.

**Steps to test this PR**
1. Checkout to `fix/3118-klarna-currency` branch.
2. Connect a Stripe account from the UK.
3. Select Pound sterling as the store currency.
4. Enable Klarna.
5. As a shopper, add a product to the page and proceed to checkout.
6. Select France as the billing country.
7. Notice that Klarna is not available as a payment method now because for France the currency is Euro which is not same as the presentment currency Pound.
8. Now connect a Stripe account from any EEA country.
9. Select Euro as the store currency.
10. As a shopper, add a product to the page and proceed to checkout.
11. Select France as the billing country.
12. Notice that Klarna is present as an available payment method.
13. Select Germany as the billing country.
14. Notice that Klarna is present as an available payment method.
15. Select UK as the billing country. Notice that Klarna is not available as a payment method now because for UK the currency is Pound which is not same as the presentment currency Euro.

**Note**
I will fix the tests

### CODE REVIEW

**Review by james-allan — CHANGES_REQUESTED** [review]
Hey @Mayisha. I think there's a little more to this. 

Stripe's docs say this: 

> If you’re based in the EEA, UK, or Switzerland, then you can transact with consumers across the EEA, UK, and Switzerland, provided the presentment currency matches the currency of the customer’s country. For example, a Swedish business can present in EUR to accept Klarna from a buyer in Germany.

It's somewhat similar to the Swedish example they give but if you follow your steps to replicate but you set your store to EUR rather than GBP, then a customer in France should be able to transact with you. That's currently not the case on develop or this branch.

The countries that Stripe list in that explainer above have their own local currency that is also valid. eg Sweden can transact in SEK or EUR, the UK can transact in GPB and EUR etc. 

I think the issue is with the `accept_only_domestic_payment` flag. It's kind of like Klarna is limited to domestic payments but on outside of these specific European examples. 

So I'm not 100% sure what the solution is here. Could we remove the `$this->accept_only_domestic_payment = true` flag on Klarna and then enforce these limitations based on the currency? 🤔

**Comment by Mayisha** [comment]
Hi @james-allan 
I have updated this PR. But looks like the issue is already fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3235. Could you confirm this? I will close this PR if the issue is already fixed with the other PR.

**Comment by james-allan** [comment]
Oh no. I'm sorry @Mayisha.

I was looking to pick up an issue last week and came across your comment [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3070#issuecomment-2124933641). I had completely forgotten about this PR and that it was resolving the same issue I fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3235.  

I think you're right. This PR is probably not needed any more.

**Comment by Mayisha** [comment]
Thanks for confirming @james-allan. 
Closing this one as the issue is fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3235 💯

**Pull request closed without merging**
