### PR TITLE
Update Stripe API version to 2024-06-20

### LINKED ISSUE #1207: Update Stripe API version to latest
The current Stripe API version used is [`2019-09-09`](https://stripe.com/docs/upgrades#2019-09-09) - we should look at updating this. 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-api.php#L17

Changelog - https://stripe.com/docs/upgrades#api-changelog

I don't see any updates between the current version and now but wanted to have this visible and checked so we can reference this.

Context - https://wordpress.org/support/topic/stripe-webhook-errors/#post-12850859

### PR DESCRIPTION
**Pull request by diegocurbelo**
Fixes #1207, #2655

## Changes proposed in this Pull Request:

This PR bumps the Stripe API version used for making requests to the Stripe API from version `2019-09-09` to `2024-06-20`.

## Testing instructions
- Verify that all checks pass correctly (including the E2E suite)

### CODE REVIEW

**Review by mattallan — COMMENTED** [review]
Nice changes here @diegocurbelo !!

There's one more instance of `end( $result->charges->data );` ([code here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/cb36e1ca42627dc39af0062dc9f336bf29edcdf6/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1111)) that wasn't updated in this PR. Does this also need to be updated?

Since this is changing a lot of areas of code, I've tested this PR through the following flows:
- [x] Purchasing a simple product
- [x] Using a new card
- [x] Using a saved card
- [x] Adding payment method via My Account
- [x] Purchasing a subscription
    - [x] Subscription with a free trial
- [x] Purchasing a pre-order
- [x] With UPE enabled
- [x] With UPE disabled
- [x] Test with APMs
    - [x] iDEAL
    - [x] Boleto
    - [x] SEPA Direct Debit

**Comment by wjrosa** [comment]
hi @diegocurbelo ! Just a heads up that the changelog and readme entries are missing 👀

**Comment by diegocurbelo** [comment]
> hi @diegocurbelo ! Just a heads up that the changelog and readme entries are missing 👀

Nice catch @wjrosa... just added them!

**Review by wjrosa — APPROVED** [review]
Changes look good and all checks are still passing 👍

**Pull request merged**
