### PR TITLE
Wrap account summary API in WP_REST_Response

### LINKED ISSUE #2268: Please wrap get_account_summary return value in new WP_REST_Response
**Describe the bug**

Props @joshheald for [noticing this](https://github.com/woocommerce/woocommerce-ios/pull/5799#discussion_r779646571). Unlike other endpoint response functions, the return value of get_account_summary is not wrapped in WP_REST_Response:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/13b254d7e16f5123c3e1110f48c78ddda586adab/includes/admin/class-wc-rest-stripe-account-controller.php#L101

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
WooCommerce Stripe 5.9.0

**Additional context**
N/A

cc @brianyu28

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #2268

## Changes proposed in this Pull Request:

All of the API responses should be wrapped in `WP_Rest_Response`, but the response on the account summary API was missing it. This PR wraps the response array in `WP_Rest_Response`.

cc @allendav @joshheald 

## Testing instructions

Make a GET request to `/wp-json/wc/v3/wc_stripe/account/summary` (e.g. by running `curl --user username:password 'http://YOUR_SITE/wp-json/wc/v3/wc_stripe/account/summary'` with [Basic Auth](https://github.com/WP-API/Basic-Auth) installed). Verify that you get back a valid JSON response with account details.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by brianyu28** [comment]
@chickenn00dle — I have two other PRs related to this endpoint (#2272, #2275) that are currently pointed towards this PR's branch since they depend on these changes. I'm thinking it probably makes more sense to wait for this PR to be approved and then merge the other two so that this one is easier to review, but if you'd prefer it done differently let me know!

**Comment by chickenn00dle** [comment]
Sounds good!

Sorry, I completely missed this one last week 🙇

**Comment by chickenn00dle** [comment]
Hey @brianyu28 

I tested and this fixes the account summary endpoint response 👍 

Just two minor things before merging:

1. When I make a request and my site is not connected to Stripe, I get the following:

```
{
    "has_pending_requirements": false,
    "has_overdue_requirements": false,
    "current_deadline": null,
    "status": "complete",
    "statement_descriptor": "",
    "store_currencies": {
        "default": "",
        "supported": [
            ""
        ]
    },
    "country": ""
}
```

Is status meant to be `complete` here?

2. Changelog/readme conflicts.

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
changelog/readme conflicts

**Comment by brianyu28** [comment]
> When I make a request and my site is not connected to Stripe, I get the following:
> Is status meant to be `complete` here?

It shouldn't be `complete` — that's fixed separately by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2275, which I'll merge into this branch before merging into `develop`.

**Comment by chickenn00dle** [comment]
Gotcha! Sorry, should have more carefully looked over the linked PRs in your first comment. Then this is good to go after the conflicts are resolved 👍

**Comment by brianyu28** [comment]
Thanks for the review! Conflicts should be resolved now.

**Review by chickenn00dle — APPROVED** [review]

**Pull request merged**
