### PR TITLE
don't call show on prequest

### PR DESCRIPTION
**Pull request by thorsten-stripe**
#### Changes proposed in this Pull Request:
`paymentRequest.show()` should not be called manually but rather `e.preventDefault();` should only be called if we want to prevent the sheet from showing.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
@roykho thanks, any chance you can add that to the RC release? It's quite important as we're planning to error if `show()` is actively called because it doesn't work consistently!

**Comment by roykho** [comment]
@thorsten-stripe not needed as we're testing off 4.0.0 branch.

**Comment by thorsten-stripe** [comment]
@roykho I mean on the release page[0] where it states  commit `7f70103` and downloading the source zip from there is on that state and therefore includes the show() call.

**Comment by roykho** [comment]
@thorsten-stripe right we don't use that..This is not a public release.

**Comment by roykho** [comment]
@thorsten-stripe I deleted it just to not cause confusion.

**Comment by michelle** [comment]
:+1:

thanks so much, thorsten 🎉

**Comment by thorsten-stripe** [comment]
@roykho perfect, thanks!

**Pull request merged**
