### PR TITLE
Use better error messages when an ajax request fails

### LINKED ISSUE #1991: Generic "error" message is sometimes displayed
**Describe the bug**

A generic `error` message is sometimes displayed.

**To Reproduce**

* Checkout attempt is made after network connection has been disabled on the machine.
* Page is refreshed while the UPE component (and not the entire checkout page!) is loading (at least in Firefox).

This happens only when UPE is enabled.

**Expected behavior**

A more informative message is displayed.

**Screenshots**

Markup on 2021-09-28 at 13:12:59

GIF: https://d.pr/i/e9wOr4

**Environment (please complete the following information):**

WC Stripe 5.6-test

### PR DESCRIPTION
**Pull request by superdav42**
closes #1991

If an ajax requests fails for many reasons only a message with the text "error" is shown at the top of the page.
This will make 3 better messages.

To test:
Load page with UPE.
Disable network by opening Network tab in chrome debug tools. Change throttling to offline. 
See that the better error message is shown.
image

Feel free to add improved error messages. 
Once this is approved we can backport it to WCPay.

### CODE REVIEW

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Hey @superdav42! The code looks good, but I found a couple of details:

**When using a saved payment method, the error message is empty**:

Screen Shot 2021-09-30 at 11 38 54

I think we need to do something similar with the error here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/78154394ec1b49c859c0ac949a25bdacb21a9ac5/client/classic/upe/index.js#L555-L558

--

**I couldn't make this work with the `Blocks Checkout`**.
After throttling to offline and clicking `Place Order` it stays `loading/working` indefinitely and no message is shown:

Screen Shot 2021-09-30 at 12 16 56

**Comment by superdav42** [comment]
> Hey @superdav42! The code looks good, but I found a couple of details:
> 
> **When using a saved payment method, the error message is empty**:
> 
> Screen Shot 2021-09-30 at 11 38 54


I traced this problem to[ this line](https://github.com/woocommerce/woocommerce/blob/trunk/assets/js/frontend/checkout.js#L563) in the core code. Saved payment methods mostly used payment token from core so they are unrelated to UPE. I'll see if I can open an issue or PR for WC core.

**Comment by superdav42** [comment]
> **I couldn't make this work with the `Blocks Checkout`**. After throttling to offline and clicking `Place Order` it stays `loading/working` indefinitely and no message is shown:
> 
> Screen Shot 2021-09-30 at 12 16 56

This seems to be a problem in the blocks plugin not the stripe gateway. It behaves exactly the same when when stripe in disabled. I'll open an issue with woocommerce blocks.

**Review by diegocurbelo — APPROVED** [review]
@superdav42 Cool, lets merge this then 🚢

**Pull request merged**
